import { productionTypes } from "@/lib/production";

export type FooterInfoPage = {
  slug: string;
  label: string;
  group: string;
  badge: string;
  title: string;
  summary: string;
  bestFor: string;
  input: string;
  output: string;
  primaryCtaLabel: string;
  primaryCtaHref: string;
  secondaryCtaLabel?: string;
  secondaryCtaHref?: string;
  steps: string[];
  examples: string[];
};

function workspace(idea: string, extra = "") {
  return `/dashboard/assistant-workspace?idea=${encodeURIComponent(idea)}${extra}`;
}

const baseFooterInfoPages: FooterInfoPage[] = [
  {
    slug: "text-to-campaign",
    label: "Text-to-Campaign",
    group: "Products",
    badge: "Campaign production",
    title: "Text-to-Campaign",
    summary: "Turn a short idea, product message, launch note or campaign brief into a structured marketing production request with hooks, copy, creative direction and delivery planning.",
    bestFor: "Product launches, service promos, ecommerce campaigns and social ads.",
    input: "A text brief, offer, product link, audience note or platform goal.",
    output: "Campaign direction, copy, visual/video needs and dashboard production workflow.",
    primaryCtaLabel: "Start Text-to-Campaign",
    primaryCtaHref: workspace("Text-to-Campaign", "&category=campaign&mode=social"),
    secondaryCtaLabel: "Browse all categories",
    secondaryCtaHref: "/categories",
    steps: ["Describe the campaign idea.", "Crelavo structures the audience, offer, channel and creative direction.", "Choose campaign outputs such as posts, visuals or product ad video.", "Start production and track delivery from the dashboard."],
    examples: ["TikTok / Reels campaign idea", "Product launch copy and video direction", "Shopify, Amazon or Trendyol product campaign", "Service business promo package", "Multi-platform caption and hashtag direction", "Product ad video production brief"]
  },
  {
    slug: "ai-video-generator",
    label: "AI Video Generator",
    group: "Products",
    badge: "AI video",
    title: "AI Video Generator",
    summary: "Create AI video requests from a short idea, scene description, product concept, self-in-video reference, multi-person dialogue or campaign direction and move into a managed production workspace.",
    bestFor: "Short ads, social clips, concept videos, product visuals, talking videos, regional culture scenes and creative tests.",
    input: "A video idea, scene prompt, visual direction, product description, person count, user reference, region/culture notes or target platform.",
    output: "A structured AI video production request with format, style, duration, optional talking-character setup and delivery expectations.",
    primaryCtaLabel: "Start AI Video",
    primaryCtaHref: workspace("AI video", "&category=video&mode=media"),
    secondaryCtaLabel: "View video categories",
    secondaryCtaHref: "/categories",
    steps: ["Write the video idea.", "Choose or confirm style, duration, people count, culture/region and target platform.", "Crelavo prepares the production request and extra-credit estimate.", "Track the video output from the dashboard."],
    examples: ["Text-to-video product clip", "Image-to-video scene", "Self-in-video talking scene", "3-person animated conversation", "Regional clothing video", "Local accent voice-over"]
  },
  {
    slug: "advanced-talking-video",
    label: "Advanced Talking Video",
    group: "Products",
    badge: "Talking video",
    title: "Advanced Talking Video",
    summary: "Create self-in-video, multi-person conversation, panel/interview, regional culture and own-voice talking video requests from one guided workspace.",
    bestFor: "Creators who want to place themselves in video, make 2/3/4/5+ or 7-8 person talking scenes, use their own voice material, or add regional clothing, local lifestyle environments and dialect/accent voice-over.",
    input: "User image/video material, person count, script/dialogue, own voice material, target region, clothing/environment notes and realistic or animated style preference.",
    output: "A structured talking-video production request with self-in-video setup, roles, voice-per-person notes, regional culture direction, material handling and credit estimate.",
    primaryCtaLabel: "Start Advanced Talking Video",
    primaryCtaHref: workspace("Advanced talking video self-in-video multi-person regional culture", "&category=talking_video&mode=media"),
    secondaryCtaLabel: "View video categories",
    secondaryCtaHref: "/categories",
    steps: ["Upload or describe user/person materials.", "Choose person count such as 2, 3, 4, 5+ or 7-8 people.", "Add own voice, separate voices, regional clothing, local environment or dialect/accent notes.", "Start the talking-video production request from the workspace."],
    examples: ["Self-in-video talking scene", "3-person conversation video", "7-8 person panel video", "Regional clothing and lifestyle scene", "Own voice-over talking video", "Dialect/accent voice-over"]
  },
  {
    slug: "ai-music-video",
    label: "AI Music Video",
    group: "Products",
    badge: "Music video",
    title: "AI Music Video",
    summary: "Plan a music video, lyric video, visualizer or beat-driven social clip with structured visual scenes and production direction.",
    bestFor: "Artists, creators, labels, lyric videos, visualizers and social music clips.",
    input: "Song idea, lyrics, mood, genre, artist direction or music video concept.",
    output: "Music video brief, visual structure, shot direction and production workflow.",
    primaryCtaLabel: "Start Music Video",
    primaryCtaHref: workspace("Music video MV", "&category=music_video&mode=media"),
    secondaryCtaLabel: "View music tools",
    secondaryCtaHref: "/categories",
    steps: ["Describe the song or music video concept.", "Define mood, visual language and target format.", "Prepare scenes, lyric/visualizer direction or MV structure.", "Start production from the workspace."],
    examples: ["Lyric video", "Visualizer", "Artist promo clip", "Beat-driven social edit", "Music video storyboard", "Short MV teaser"]
  },
  {
    slug: "series-film-studio",
    label: "Series / Film Studio",
    group: "Products",
    badge: "Story studio",
    title: "Series / Film Studio",
    summary: "Develop film, short drama, trailer, series or studio-style story production requests with script, scenes, character direction and delivery planning.",
    bestFor: "Short films, drama concepts, trailers, episodic ideas and story-driven AI video.",
    input: "Story idea, character setup, episode premise, trailer concept or script outline.",
    output: "Structured story production plan, scene direction and workspace production request.",
    primaryCtaLabel: "Start Series / Film Studio",
    primaryCtaHref: workspace("Series film studio", "&category=studio&mode=media"),
    secondaryCtaLabel: "Browse video categories",
    secondaryCtaHref: "/categories",
    steps: ["Describe the story or scene.", "Define format: short film, trailer, series or drama.", "Prepare characters, tone, scenes and delivery expectations.", "Continue into production workspace."],
    examples: ["Short film idea", "Drama trailer", "Series pilot concept", "Character scene plan", "Story teaser", "Film-style social clip"]
  },
  {
    slug: "ai-agents",
    label: "AI Agents",
    group: "Products",
    badge: "AI agents",
    title: "AI Agents",
    summary: "Create AI agent, digital brand face, autonomous content assistant or virtual operator production requests from one guided workspace.",
    bestFor: "Brands, creators, agencies, support workflows and autonomous content operations.",
    input: "Agent purpose, brand role, personality, channels and task expectations.",
    output: "AI agent concept, avatar/brand direction, workflow plan and production request.",
    primaryCtaLabel: "Start AI Agent",
    primaryCtaHref: workspace("AI Agents", "&category=ai_agent&mode=project"),
    secondaryCtaLabel: "View agent category",
    secondaryCtaHref: "/categories",
    steps: ["Describe what the agent should do.", "Define role, tone, audience and channels.", "Prepare agent identity and production modules.", "Continue into workspace for delivery planning."],
    examples: ["AI influencer", "Digital brand face", "Social media agent", "Customer education assistant", "Autonomous campaign helper", "Live avatar concept"]
  },
  {
    slug: "global-localization",
    label: "Global Localization",
    group: "Products",
    badge: "Localization",
    title: "Global Localization",
    summary: "Adapt campaigns, videos, websites or creative assets for another language, country, culture, audience, regional clothing, local environment or dialect voice context.",
    bestFor: "Global launches, local campaigns, multilingual content, yöresel/regional videos and local market adaptation.",
    input: "Original content, target country/language, audience, region, clothing/environment notes, local accent or adaptation goal.",
    output: "Localized creative direction, regional culture notes, dialect/voice direction and production workflow.",
    primaryCtaLabel: "Start Localization",
    primaryCtaHref: workspace("Global localization", "&category=localization&mode=media"),
    secondaryCtaLabel: "View localization options",
    secondaryCtaHref: "/categories",
    steps: ["Choose target market and language.", "Provide original campaign, video or asset direction.", "Crelavo adapts tone, culture, visuals and delivery expectations.", "Start localized production."],
    examples: ["Turkish to English campaign", "US market adaptation", "Arabic social ad direction", "Localized subtitle/dubbing brief", "Country-specific product promo", "Global launch variant"]
  },
  {
    slug: "brand-kit",
    label: "Brand Kit",
    group: "Products",
    badge: "Brand system",
    title: "Brand Kit",
    summary: "Prepare brand identity, reusable visual direction, colors, logo usage notes and delivery assets for future production workflows.",
    bestFor: "Startups, creators, ecommerce stores, agencies and recurring brand production.",
    input: "Brand name, style direction, audience, colors, references and usage needs.",
    output: "Brand kit request with visual identity direction, assets and reusable production guidance.",
    primaryCtaLabel: "Start Brand Kit",
    primaryCtaHref: workspace("Brand kit", "&category=brand_kit&mode=brand"),
    secondaryCtaLabel: "Open brand kit dashboard",
    secondaryCtaHref: "/dashboard/brand-kit",
    steps: ["Describe the brand and audience.", "Choose style, tone and asset needs.", "Prepare brand kit direction and deliverables.", "Use the brand kit in later productions."],
    examples: ["Startup brand kit", "Ecommerce store visual system", "Social media brand assets", "Logo usage notes", "Color and typography direction", "Reusable campaign identity"]
  },
  {
    slug: "document-pack",
    label: "Document Pack",
    group: "Products",
    badge: "Documents",
    title: "Document Pack",
    summary: "Create structured document, pitch deck, PDF, guide, sales material or business file production requests.",
    bestFor: "Pitch decks, guides, reports, business documents and sales PDFs.",
    input: "Topic, audience, sections, goal, brand direction and file type.",
    output: "Document production plan, structure, copy direction and delivery package.",
    primaryCtaLabel: "Start Document Pack",
    primaryCtaHref: workspace("Document pack", "&category=document_pack&mode=project"),
    secondaryCtaLabel: "Browse document categories",
    secondaryCtaHref: "/categories",
    steps: ["Describe the document goal.", "Define audience, sections and format.", "Crelavo prepares structure and delivery expectations.", "Continue to production workspace."],
    examples: ["Pitch deck", "PDF guide", "Sales one-pager", "Brand document", "Training file", "Business proposal"]
  },
  {
    slug: "image-to-video",
    label: "Image to Video",
    group: "Video Tools",
    badge: "Image-to-video",
    title: "Image to Video",
    summary: "Turn a still image, product photo, character image or scene reference into an AI video production request.",
    bestFor: "Animating product images, character shots, campaign visuals and concept frames.",
    input: "Image reference plus desired movement, mood, duration and target platform.",
    output: "Image-to-video production request with motion direction and delivery expectations.",
    primaryCtaLabel: "Start Image to Video",
    primaryCtaHref: workspace("Image to video", "&category=video&mode=media"),
    secondaryCtaLabel: "View video tools",
    secondaryCtaHref: "/categories",
    steps: ["Upload or describe the image.", "Define camera movement and action.", "Choose video purpose and format.", "Start provider production."],
    examples: ["Product photo animation", "Character image movement", "Scene camera push-in", "Social post animation", "Ad visual motion", "Brand image video"]
  },
  {
    slug: "text-to-video",
    label: "Text to Video",
    group: "Video Tools",
    badge: "Text-to-video",
    title: "Text to Video",
    summary: "Create an AI video from a written scene, product description, ad concept or story idea.",
    bestFor: "Fast video drafts, ads, cinematic clips, product concepts and social posts.",
    input: "Text prompt, scene description, action, style and target duration.",
    output: "Text-to-video production request with format, style and delivery path.",
    primaryCtaLabel: "Start Text to Video",
    primaryCtaHref: workspace("Text to video", "&category=video&mode=media"),
    secondaryCtaLabel: "Browse AI video",
    secondaryCtaHref: "/categories",
    steps: ["Describe the video scene.", "Confirm style and platform.", "Crelavo prepares production details.", "Start video generation workflow."],
    examples: ["Product scene", "Cinematic city shot", "Social ad clip", "Character action", "Short promo", "Concept video"]
  },
  {
    slug: "seedance-2-video",
    label: "Seedance 2.0 Video",
    group: "Video Tools",
    badge: "Seedance workflow",
    title: "Seedance 2.0 Video",
    summary: "Prepare video requests optimized for Seedance-style generation, including short scenes, references and motion direction.",
    bestFor: "High-quality short video scenes, reference-based clips and cinematic movement tests.",
    input: "Scene prompt, reference image, camera movement, subject and duration goal.",
    output: "Seedance-ready video request with visual and motion guidance.",
    primaryCtaLabel: "Start Seedance Video",
    primaryCtaHref: workspace("Seedance 2.0 video", "&category=video&mode=media"),
    secondaryCtaLabel: "View AI video tools",
    secondaryCtaHref: "/categories",
    steps: ["Prepare scene and optional references.", "Define motion/camera direction.", "Set output target.", "Continue to workspace."],
    examples: ["Reference image to clip", "Cinematic short scene", "Character motion", "Product movement", "Fashion shot", "Atmospheric video"]
  },
  {
    slug: "ugc-video",
    label: "UGC Video",
    group: "Video Tools",
    badge: "UGC ads",
    title: "UGC Video",
    summary: "Plan user-generated-content style product ads, testimonial clips, casual presenter scripts and social-ready production briefs.",
    bestFor: "Ecommerce ads, TikTok/Reels product promos and creator-style sales videos.",
    input: "Product, offer, target buyer, tone, platform and key message.",
    output: "UGC video direction, hook, script, creator tone and production workflow.",
    primaryCtaLabel: "Start UGC Video",
    primaryCtaHref: workspace("UGC video", "&category=campaign&mode=social"),
    secondaryCtaLabel: "View campaign tools",
    secondaryCtaHref: "/categories",
    steps: ["Describe product and offer.", "Choose creator tone and platform.", "Generate UGC hook/script direction.", "Start production."],
    examples: ["TikTok product review", "Creator testimonial", "Before/after ad", "Casual sales pitch", "Unboxing concept", "Problem-solution UGC"]
  },
  {
    slug: "stickman-animation",
    label: "Stickman Animation",
    group: "Video Tools",
    badge: "Animation",
    title: "Stickman Animation",
    summary: "Create simple stickman animation concepts for education, comedy, explanation or social storytelling.",
    bestFor: "Educational explainers, fun sketches, simple story videos and social clips.",
    input: "Topic, joke, lesson, scene flow or action idea.",
    output: "Stickman animation brief, scene structure and production request.",
    primaryCtaLabel: "Start Stickman Animation",
    primaryCtaHref: workspace("Stickman animation", "&category=stickman_animation&mode=media"),
    secondaryCtaLabel: "Browse animation tools",
    secondaryCtaHref: "/categories",
    steps: ["Describe the idea or lesson.", "Define scene flow and tone.", "Prepare simple animation direction.", "Start production."],
    examples: ["Funny stickman sketch", "Educational mini lesson", "Explainer animation", "Simple story", "Training clip", "Social cartoon"]
  },
  {
    slug: "product-ad-video",
    label: "Product Ad Video",
    group: "Video Tools",
    badge: "Product ads",
    title: "Product Ad Video",
    summary: "Turn a product, product link or offer into a structured ad video production request.",
    bestFor: "Shopify, Amazon, Trendyol, direct ecommerce and product launch ads.",
    input: "Product link or description, target buyer, offer and platform.",
    output: "Ad video brief, hook, scenes, voice/subtitle direction and production workflow.",
    primaryCtaLabel: "Start Product Ad Video",
    primaryCtaHref: workspace("Product ad video", "&category=campaign&mode=commerce"),
    secondaryCtaLabel: "View ecommerce tools",
    secondaryCtaHref: "/categories",
    steps: ["Provide product or link.", "Define buyer and offer.", "Generate ad structure and production needs.", "Start video production."],
    examples: ["Shopify product ad", "Amazon listing video", "Trendyol campaign", "Product launch ad", "Feature-benefit video", "Discount campaign video"]
  },
  {
    slug: "long-film-series-clipping",
    label: "Long Film/Series Clipping",
    group: "Video Tools",
    badge: "Clipping",
    title: "Long Film/Series Clipping",
    summary: "Prepare long video, episode or film content for short clips, highlights, hooks and social exports.",
    bestFor: "Podcasts, series, webinars, films, episodes and long-form creator content.",
    input: "Long video, episode context, desired clip style and target platform.",
    output: "Clip extraction plan, hook direction, subtitle needs and delivery workflow.",
    primaryCtaLabel: "Start Clipping",
    primaryCtaHref: workspace("Long film series clipping", "&category=video_clipping&mode=media"),
    secondaryCtaLabel: "Open productions dashboard",
    secondaryCtaHref: "/dashboard/productions",
    steps: ["Upload or describe long content.", "Define target platform and clip type.", "Prepare highlight/shorts plan.", "Start clipping workflow."],
    examples: ["Podcast clips", "Best scene extraction", "Shorts/Reels cuts", "Webinar highlights", "Trailer moments", "Funny/emotional clip selection"]
  },
  {
    slug: "social-campaign-video",
    label: "Social Campaign Video",
    group: "Video Tools",
    badge: "Social video",
    title: "Social Campaign Video",
    summary: "Create platform-specific video campaign requests for TikTok, Reels, Shorts, LinkedIn or paid social.",
    bestFor: "Social launches, paid ads, creator campaigns and multi-platform content.",
    input: "Campaign goal, platform, product/service and target audience.",
    output: "Social video structure, hooks, captions and production workflow.",
    primaryCtaLabel: "Start Social Campaign Video",
    primaryCtaHref: workspace("Social campaign video", "&category=campaign&mode=social"),
    secondaryCtaLabel: "View campaign category",
    secondaryCtaHref: "/categories",
    steps: ["Choose social platform.", "Describe offer and audience.", "Prepare hooks and scene direction.", "Start production."],
    examples: ["Reels launch video", "TikTok ad", "Shorts promo", "LinkedIn product post", "Social teaser", "Paid social concept"]
  },
  {
    slug: "music-video-mv",
    label: "Music Video / MV",
    group: "Music and Audio Tools",
    badge: "MV",
    title: "Music Video / MV",
    summary: "Plan a music video from lyrics, song mood, artist direction or visual references.",
    bestFor: "Artists, labels, creators and music-driven video production.",
    input: "Song, lyrics, genre, mood, artist identity and visual concept.",
    output: "MV concept, shot direction, visual style and production workflow.",
    primaryCtaLabel: "Start MV",
    primaryCtaHref: workspace("Music video MV", "&category=music_video&mode=media"),
    secondaryCtaLabel: "View music tools",
    secondaryCtaHref: "/categories",
    steps: ["Describe the song and mood.", "Choose visual story or performance direction.", "Prepare MV scene structure.", "Start production."],
    examples: ["Artist performance MV", "Narrative music video", "Lyric-driven clip", "Dance edit", "Mood visual", "Short MV teaser"]
  },
  {
    slug: "lyric-video",
    label: "Lyric Video",
    group: "Music and Audio Tools",
    badge: "Lyrics",
    title: "Lyric Video",
    summary: "Create a lyric video production request with typography direction, mood, background visuals and timing expectations.",
    bestFor: "Song releases, YouTube lyric videos, teasers and social edits.",
    input: "Lyrics, song mood, artist/brand direction and format.",
    output: "Lyric video style, text treatment and production brief.",
    primaryCtaLabel: "Start Lyric Video",
    primaryCtaHref: workspace("Lyric video", "&category=music_video&mode=media"),
    secondaryCtaLabel: "View music tools",
    secondaryCtaHref: "/categories",
    steps: ["Provide lyrics or song direction.", "Choose visual mood and typography style.", "Prepare timing and delivery notes.", "Start production."],
    examples: ["YouTube lyric video", "Animated lyrics", "Minimal lyric visual", "Social lyric teaser", "Release promo", "Kinetic text concept"]
  },
  {
    slug: "visualizer",
    label: "Visualizer",
    group: "Music and Audio Tools",
    badge: "Visualizer",
    title: "Visualizer",
    summary: "Prepare looping or evolving visualizer concepts for music, brand sound, podcasts or audio-first content.",
    bestFor: "Music releases, podcasts, ambient visuals and YouTube audio content.",
    input: "Track mood, audio theme, visual style and target format.",
    output: "Visualizer brief, visual motif and production workflow.",
    primaryCtaLabel: "Start Visualizer",
    primaryCtaHref: workspace("Visualizer", "&category=music_video&mode=media"),
    secondaryCtaLabel: "View music tools",
    secondaryCtaHref: "/categories",
    steps: ["Describe audio mood.", "Choose visual motif.", "Set format and loop direction.", "Start production."],
    examples: ["Album visualizer", "Podcast background", "Ambient loop", "Beat visual", "Brand audio visual", "Release teaser"]
  },
  {
    slug: "voice-over",
    label: "Voice-over",
    group: "Music and Audio Tools",
    badge: "Voice",
    title: "Voice-over",
    summary: "Plan voice-over production for ads, explainers, product videos, tutorials and localization.",
    bestFor: "Narration, product videos, tutorials, ads, explainers and multilingual content.",
    input: "Script, language, tone, speaker style and target video/use case.",
    output: "Voice-over brief, script direction and production workflow.",
    primaryCtaLabel: "Start Voice-over",
    primaryCtaHref: workspace("Voice-over video", "&category=video&mode=media"),
    secondaryCtaLabel: "Open dubbing tools",
    secondaryCtaHref: "/dashboard/dubbing",
    steps: ["Provide script or message.", "Choose language and tone.", "Prepare voice direction.", "Start production."],
    examples: ["Ad narration", "Explainer voice", "Tutorial voice", "Product demo", "Localized narration", "Brand presenter voice"]
  },
  {
    slug: "ai-dubbing-lip-sync",
    label: "AI Dubbing / Lip-Sync",
    group: "Music and Audio Tools",
    badge: "Dubbing",
    title: "AI Dubbing / Lip-Sync",
    summary: "Prepare dubbing, translation, voice replacement or lip-sync production requests for videos.",
    bestFor: "Localization, video translation, presenter content and multilingual campaigns.",
    input: "Source video/audio, target language, speaker/tone and sync needs.",
    output: "Dubbing/lip-sync workflow with language, voice and delivery expectations.",
    primaryCtaLabel: "Open Dubbing Workspace",
    primaryCtaHref: "/dashboard/dubbing",
    secondaryCtaLabel: "Start localization request",
    secondaryCtaHref: workspace("AI Dubbing Lip-Sync", "&category=localization&mode=media"),
    steps: ["Provide source video/audio.", "Choose target language and voice direction.", "Prepare dubbing or lip-sync plan.", "Start production workflow."],
    examples: ["English dubbing", "Turkish localization", "Presenter lip-sync", "Product video translation", "Course dubbing", "Ad localization"]
  },
  {
    slug: "language-market-adaptation",
    label: "Language and Market Adaptation",
    group: "Music and Audio Tools",
    badge: "Market adaptation",
    title: "Language and Market Adaptation",
    summary: "Adapt content for another market by changing language, cultural references, audience tone and creative positioning.",
    bestFor: "International campaigns, regional ecommerce, multilingual ads and local market launches.",
    input: "Original content, target market, language and adaptation goal.",
    output: "Market-specific creative direction and production brief.",
    primaryCtaLabel: "Start Market Adaptation",
    primaryCtaHref: workspace("Language and market adaptation", "&category=localization&mode=media"),
    secondaryCtaLabel: "View localization",
    secondaryCtaHref: "/categories",
    steps: ["Choose target country/language.", "Provide original content.", "Prepare adaptation notes.", "Start localized production."],
    examples: ["US market version", "Arabic campaign adaptation", "German product page angle", "Spanish captions", "Localized video idea", "Regional sales message"]
  },
  {
    slug: "website",
    label: "Website",
    group: "Business and File Production",
    badge: "Website production",
    title: "Website",
    summary: "Create landing page, business website, ecommerce storefront or website + admin panel production requests.",
    bestFor: "Businesses, founders, ecommerce stores, service brands and launch pages.",
    input: "Website goal, pages, brand direction, features, audience and delivery needs.",
    output: "Website production brief, page plan, UI direction and source/package delivery workflow.",
    primaryCtaLabel: "Start Website Production",
    primaryCtaHref: workspace("Website", "&category=website&mode=project"),
    secondaryCtaLabel: "View website category",
    secondaryCtaHref: "/categories",
    steps: ["Describe website purpose.", "Choose page/module needs.", "Prepare project scope and delivery package.", "Start workspace production."],
    examples: ["Landing page", "Business website", "Ecommerce website", "Website with admin", "Product launch site", "Portfolio/site package"]
  },
  {
    slug: "saas",
    label: "SaaS",
    group: "Business and File Production",
    badge: "SaaS production",
    title: "SaaS",
    summary: "Plan SaaS dashboards, auth flows, billing screens, admin panels and app UI production requests.",
    bestFor: "SaaS founders, MVPs, dashboards, AI tools and internal platforms.",
    input: "SaaS idea, user roles, screens, modules, billing and workflow needs.",
    output: "SaaS project brief, screen plan, module structure and delivery package.",
    primaryCtaLabel: "Start SaaS Production",
    primaryCtaHref: workspace("SaaS", "&category=saas&mode=project"),
    secondaryCtaLabel: "View SaaS category",
    secondaryCtaHref: "/categories",
    steps: ["Describe SaaS product.", "Define users, screens and modules.", "Prepare dashboard/auth/billing scope.", "Start production request."],
    examples: ["AI SaaS dashboard", "Customer portal", "Admin + billing", "Analytics dashboard", "Team workspace", "MVP screen pack"]
  },
  {
    slug: "mobile-app",
    label: "Mobile App",
    group: "Business and File Production",
    badge: "Mobile app",
    title: "Mobile App",
    summary: "Prepare mobile app, iOS/Android, Expo or app UI production requests with screens and delivery planning.",
    bestFor: "App founders, mobile MVPs, marketplaces, creator tools and business apps.",
    input: "App idea, screens, users, features, platform and style direction.",
    output: "Mobile app brief, screen list, UI direction and delivery package.",
    primaryCtaLabel: "Start Mobile App Production",
    primaryCtaHref: workspace("Mobile App", "&category=mobile_app&mode=project"),
    secondaryCtaLabel: "View app category",
    secondaryCtaHref: "/categories",
    steps: ["Describe app idea.", "Choose platform and screens.", "Prepare app flow and delivery package.", "Start production."],
    examples: ["iOS app screens", "Android app UI", "Expo starter app", "Mobile marketplace", "Creator app", "Booking app"]
  },
  {
    slug: "admin-panel",
    label: "Admin Panel",
    group: "Business and File Production",
    badge: "Admin panels",
    title: "Admin Panel",
    summary: "Create admin panel, dashboard, operations tool or internal management interface production requests.",
    bestFor: "SaaS admin, ecommerce operations, user management, reporting and internal tools.",
    input: "Admin roles, tables, actions, modules, data and workflow requirements.",
    output: "Admin panel project brief, screen plan, module list and delivery package.",
    primaryCtaLabel: "Start Admin Panel Production",
    primaryCtaHref: workspace("Admin Panel", "&category=admin_project&mode=project"),
    secondaryCtaLabel: "View admin project category",
    secondaryCtaHref: "/categories",
    steps: ["Describe admin operations.", "Define users, tables and actions.", "Prepare modules and permissions.", "Start production request."],
    examples: ["User management", "Payments dashboard", "Content manager", "Analytics admin", "Operations panel", "Internal CRM"]
  },
  {
    slug: "pitch-deck-pdf",
    label: "Pitch Deck / PDF",
    group: "Business and File Production",
    badge: "PDF documents",
    title: "Pitch Deck / PDF",
    summary: "Prepare pitch decks, PDF documents, business guides, sales decks and structured file deliverables.",
    bestFor: "Startups, agencies, founders, educators and sales teams.",
    input: "Topic, audience, slide/page count, message, brand direction and goal.",
    output: "Document structure, copy direction, visual plan and delivery package.",
    primaryCtaLabel: "Start Pitch Deck / PDF",
    primaryCtaHref: workspace("Pitch Deck PDF", "&category=document_pack&mode=project"),
    secondaryCtaLabel: "View document tools",
    secondaryCtaHref: "/categories",
    steps: ["Describe the deck/document goal.", "Define audience and sections.", "Prepare copy and visual structure.", "Start production."],
    examples: ["Startup pitch deck", "Investor PDF", "Sales deck", "Training PDF", "Product guide", "Business proposal"]
  },
  {
    slug: "visual-image-pack",
    label: "Visual / Image Pack",
    group: "Business and File Production",
    badge: "Visuals",
    title: "Visual / Image Pack",
    summary: "Create image packs, campaign visuals, product visuals, social graphics or reusable visual assets.",
    bestFor: "Brands, ecommerce stores, creators, social campaigns and product launches.",
    input: "Visual goal, product/brand details, style direction, quantity and format.",
    output: "Image pack brief, visual direction, format list and delivery workflow.",
    primaryCtaLabel: "Start Visual Pack",
    primaryCtaHref: workspace("Visual Image Pack", "&category=image&mode=media"),
    secondaryCtaLabel: "Browse image tools",
    secondaryCtaHref: "/categories",
    steps: ["Describe visual asset need.", "Choose format and quantity.", "Prepare style and delivery requirements.", "Start production."],
    examples: ["Product image pack", "Social visuals", "Campaign banners", "Brand assets", "Ad image set", "Website visual pack"]
  },
  {
    slug: "categories",
    label: "Categories",
    group: "Platform",
    badge: "Platform navigation",
    title: "Categories",
    summary: "Browse all Crelavo production categories and choose the right workflow for video, campaign, website, app, brand, document or automation work.",
    bestFor: "Users who are not sure which production type to start with.",
    input: "Choose a category or compare production paths.",
    output: "A selected production category and path into the workspace.",
    primaryCtaLabel: "Open Categories",
    primaryCtaHref: "/categories",
    secondaryCtaLabel: "Open workspace",
    secondaryCtaHref: "/dashboard/assistant-workspace",
    steps: ["Browse available production categories.", "Compare what each category is for.", "Choose the best fit.", "Start production from the selected path."],
    examples: ["AI video", "Website", "SaaS", "Brand kit", "Document pack", "Ecommerce campaign"]
  },
  {
    slug: "pricing",
    label: "Pricing",
    group: "Platform",
    badge: "Credits",
    title: "Pricing",
    summary: "Review credit packages, subscriptions, top-ups and production capacity before starting a request.",
    bestFor: "Users choosing a plan or estimating production capacity.",
    input: "Budget, production frequency and expected output type.",
    output: "Recommended package or top-up path.",
    primaryCtaLabel: "View Pricing",
    primaryCtaHref: "/pricing",
    secondaryCtaLabel: "Open credits",
    secondaryCtaHref: "/dashboard/credits",
    steps: ["Compare plans and credits.", "Choose subscription or top-up.", "Review package benefits.", "Start production after credits are ready."],
    examples: ["Pro plan", "Business plan", "Top-up credits", "Team package", "Monthly credits", "Production capacity"]
  },
  {
    slug: "dashboard",
    label: "Dashboard",
    group: "Platform",
    badge: "Workspace",
    title: "Dashboard",
    summary: "Open the user dashboard to manage credits, productions, delivery links, settings and workspace activity.",
    bestFor: "Signed-in users managing active work.",
    input: "Account login.",
    output: "Dashboard access to production and account tools.",
    primaryCtaLabel: "Open Dashboard",
    primaryCtaHref: "/dashboard",
    secondaryCtaLabel: "Start workspace",
    secondaryCtaHref: "/dashboard/assistant-workspace",
    steps: ["Sign in.", "Open dashboard.", "Check credits and productions.", "Continue production work."],
    examples: ["Production tracking", "Credit balance", "Settings", "Delivery links", "Workspace access", "Account tools"]
  },
  {
    slug: "my-productions",
    label: "My Productions",
    group: "Platform",
    badge: "Production tracking",
    title: "My Productions",
    summary: "Track production requests, status, previews, revisions and final delivery links from one dashboard page.",
    bestFor: "Users with active or completed production requests.",
    input: "Existing production requests.",
    output: "Status, previews, final files and revision actions.",
    primaryCtaLabel: "Open My Productions",
    primaryCtaHref: "/dashboard/productions",
    secondaryCtaLabel: "Start new request",
    secondaryCtaHref: "/dashboard/assistant-workspace",
    steps: ["Open the productions list.", "Check status and preview links.", "Request revisions if needed.", "Download final delivery."],
    examples: ["Queued productions", "Ready files", "Revision requests", "Delivery ZIP", "Provider status", "Final video preview"]
  },
  {
    slug: "credit-packages",
    label: "Credit Packages",
    group: "Platform",
    badge: "Credits",
    title: "Credit Packages",
    summary: "Buy or manage credits used for AI production requests, provider jobs and delivery packages.",
    bestFor: "Users preparing to start or continue production work.",
    input: "Plan choice or top-up need.",
    output: "Available credits for production.",
    primaryCtaLabel: "Open Credit Packages",
    primaryCtaHref: "/dashboard/credits",
    secondaryCtaLabel: "View pricing",
    secondaryCtaHref: "/pricing",
    steps: ["Review current credits.", "Choose package or top-up.", "Complete checkout.", "Start production with available credits."],
    examples: ["Monthly plan credits", "One-time top-up", "Reserved credits", "Production budget", "Credit balance", "Package upgrade"]
  },
  {
    slug: "connections",
    label: "Connections",
    group: "Platform",
    badge: "Integrations",
    title: "Connections",
    summary: "Manage connected social accounts, stores, publishing targets and integration readiness.",
    bestFor: "Users who want future publishing, exports, store workflows or social account connection.",
    input: "Platform/account connection goal.",
    output: "Connected account or integration management path.",
    primaryCtaLabel: "Open Connections",
    primaryCtaHref: "/dashboard/connections",
    secondaryCtaLabel: "Open dashboard",
    secondaryCtaHref: "/dashboard",
    steps: ["Open connections.", "Choose platform or store.", "Review token/status.", "Use connected targets in production."],
    examples: ["Instagram", "TikTok", "YouTube", "LinkedIn", "Shopify", "Store publishing"]
  }
];

function slugify(value: string) {
  return value.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

const existingLabels = new Set(baseFooterInfoPages.map((page) => page.label));
const existingSlugs = new Set(baseFooterInfoPages.map((page) => page.slug));

const generatedProductionInfoPages: FooterInfoPage[] = productionTypes
  .map((type) => ({ type, slug: slugify(type.id) }))
  .filter(({ type, slug }) => !existingLabels.has(type.label) && !existingSlugs.has(slug))
  .map(({ type, slug }) => ({
    slug,
    label: type.label,
    group: "More Production Categories",
    badge: "Production category",
    title: type.label,
    summary: type.description,
    bestFor: `${type.label} projects and managed Crelavo production requests.`,
    input: "A clear production goal, preferred style, target platform, materials and delivery expectations.",
    output: "A structured production request with credit estimate, workflow direction and dashboard delivery path.",
    primaryCtaLabel: `Start ${type.label}`,
    primaryCtaHref: workspace(type.label, `&category=${encodeURIComponent(type.id)}&mode=project`),
    secondaryCtaLabel: "Browse categories",
    secondaryCtaHref: "/categories",
    steps: ["Review what this category is for.", "Prepare the idea, materials and delivery goal.", "Open the production workspace with this category selected.", "Track the request from the dashboard."],
    examples: [`${type.label} production brief`, `${type.label} delivery package`, `${type.label} creative direction`, `${type.label} dashboard request`]
  }));

export const footerInfoPages: FooterInfoPage[] = [...baseFooterInfoPages, ...generatedProductionInfoPages];
export const footerInfoPageMap = new Map(footerInfoPages.map((page) => [page.slug, page]));

export function footerInfoHref(slug: string) {
  return `/products/${slug}`;
}

export function productionInfoHref(idOrLabel: string) {
  return footerInfoHref(slugify(idOrLabel));
}
