import type { HomeShowcaseSlide } from "@/components/HomeShowcaseSlider";

export type ShowcaseItem = HomeShowcaseSlide & {
  id: string;
  group: "feature" | "category";
  eyebrow: string;
  longDescription: string;
  videoTitle: string;
  videoDescription: string;
  videoUrl?: string;
  highlights: string[];
  workflow: string[];
  bestFor: string[];
  primaryCtaLabel: string;
  primaryCtaHref: string;
  secondaryCtaLabel: string;
  secondaryCtaHref: string;
};

export const featureShowcaseItems: ShowcaseItem[] = [
  {
    id: "explore-samples",
    group: "feature",
    title: "Explore samples",
    kicker: "Samples",
    eyebrow: "Sample output feed",
    description: "Browse large sample outputs and open dedicated detail pages.",
    longDescription: "Explore samples is the visual entry point for Crelavo. Users can browse large AI production examples, open a dedicated sample page, review details and move directly into a similar production workflow.",
    href: "/showcase/explore-samples",
    tone: "cyan",
    imageUrl: "https://cdn.hailuoai.video/moss/prod/2026-07-05-03/image/1783192157407622951-1783192157402.png",
    videoTitle: "Explore samples preview",
    videoDescription: "A cinematic overview of Crelavo's sample output feed with English voice-over, background music and brand watermark.",
    videoUrl: "https://cdn.hailuoai.video/moss/prod/2026-07-05-05/video/1783200420847185558-1783200420793.mp4",
    highlights: ["Large visual output feed", "Dedicated detail pages for every sample", "Fast route from inspiration to production", "Useful for seeing what Crelavo can create"],
    workflow: ["Browse premium sample outputs", "Open a sample detail page", "Review the production idea and use case", "Start a similar production from the assistant"],
    bestFor: ["New visitors", "Output discovery", "Creative inspiration", "Fast sample-to-production flow"],
    primaryCtaLabel: "Explore samples",
    primaryCtaHref: "#sample-outputs",
    secondaryCtaLabel: "Open assistant",
    secondaryCtaHref: "/dashboard/assistant-workspace"
  },
  {
    id: "all-tools",
    group: "feature",
    title: "All Tools",
    kicker: "Catalog",
    eyebrow: "Tool catalog",
    description: "Open the full tool catalog and choose the right production entry.",
    longDescription: "All Tools is the catalog page for Crelavo's production entries. Users can choose a specific tool or category, then continue into the assistant workflow that best matches their request.",
    href: "/showcase/all-tools",
    tone: "purple",
    imageUrl: "https://cdn.hailuoai.video/moss/prod/2026-07-05-03/image/1783192261949279707-1783192261944.png",
    videoTitle: "All Tools preview",
    videoDescription: "A guided overview of the full Crelavo tool catalog, showing how customers choose the right production entry and move into the assistant workflow.",
    highlights: ["Full tool catalog", "Clear production entry points", "Useful for users who know what they want", "Works together with Omni Assistant"],
    workflow: ["Open the tool catalog", "Choose a production tool", "Review the matching workflow", "Start the request with Crelavo"],
    bestFor: ["Tool discovery", "Production categories", "Direct workflow access", "Power users"],
    primaryCtaLabel: "Open all tools",
    primaryCtaHref: "/categories",
    secondaryCtaLabel: "Open assistant",
    secondaryCtaHref: "/dashboard/assistant-workspace"
  },
  {
    id: "seedance-video-generation",
    group: "feature",
    title: "Seedance video generation",
    kicker: "Video engine",
    eyebrow: "AI video engine",
    description: "Fast cinematic clips, image-to-video direction and short-form motion workflows.",
    longDescription: "Seedance video generation helps users turn a product idea, visual reference or short creative brief into cinematic motion. It is designed for short-form ads, social hooks, product scenes, storytelling clips and fast iteration before a full production package is assembled.",
    href: "/showcase/seedance-video-generation",
    tone: "cyan",
    imageUrl: "https://cdn.hailuoai.video/moss/prod/2026-07-05-05/image/1783199248024877461-1783199248022.png",
    videoTitle: "Seedance workflow preview",
    videoDescription: "A dedicated preview area for an explainer or demo video showing prompt-to-video, image-to-video and campaign-ready clip creation.",
    highlights: ["Prompt-to-video and image-to-video workflows", "Short cinematic clips for ads, stories and product showcases", "Useful for social hooks, MV-style clips and campaign previews", "Can connect into Crelavo production packages"],
    workflow: ["Start with a product, idea, brief or visual reference", "Crelavo turns the request into a video-ready creative direction", "The video engine generates motion previews", "Approved outputs can move into campaign, website or delivery packages"],
    bestFor: ["Product ad clips", "Social media hooks", "Cinematic campaign previews", "Short storytelling scenes"],
    primaryCtaLabel: "Create AI video",
    primaryCtaHref: "/tools/ai-video-generator",
    secondaryCtaLabel: "Open assistant",
    secondaryCtaHref: "/dashboard/assistant-workspace"
  },
  {
    id: "canvas-workspace",
    group: "feature",
    title: "Canvas workspace",
    kicker: "Workspace",
    eyebrow: "Visual production board",
    description: "Collect prompts, assets, outputs and production notes in one visual board.",
    longDescription: "Canvas workspace is the visual planning layer for Crelavo productions. It gives users a place to collect prompts, references, generated outputs, brand files, video ideas and delivery notes before turning everything into a managed project.",
    href: "/showcase/canvas-workspace",
    tone: "purple",
    imageUrl: "https://cdn.hailuoai.video/moss/prod/2026-07-05-05/image/1783199267655595223-1783199267649.png",
    videoTitle: "Canvas workspace overview",
    videoDescription: "A video area for showing how users organize assets, prompts, comments and production outputs visually.",
    highlights: ["Visual organization for prompts and generated assets", "Useful for comparing outputs and planning revisions", "Keeps production notes close to creative materials", "Designed for multi-step website, video and brand projects"],
    workflow: ["Collect references and production notes", "Place generated images, videos and files into one workspace", "Review versions and decide next actions", "Move approved assets into final delivery"],
    bestFor: ["Multi-asset campaigns", "Brand projects", "Video planning", "Client review workflows"],
    primaryCtaLabel: "Open workspace",
    primaryCtaHref: "/dashboard/assistant-workspace",
    secondaryCtaLabel: "View productions",
    secondaryCtaHref: "/dashboard/productions"
  },
  {
    id: "assets-library",
    group: "feature",
    title: "Assets library",
    kicker: "Materials",
    eyebrow: "Reusable material hub",
    description: "Reuse product images, brand files, voice references, PDFs and videos across productions.",
    longDescription: "Assets library is where production materials become reusable. Users can keep product photos, logos, brand references, scripts, voice references, videos and documents available for future campaigns instead of starting from zero each time.",
    href: "/showcase/assets-library",
    tone: "green",
    imageUrl: "https://cdn.hailuoai.video/moss/prod/2026-07-05-05/image/1783199284177175093-1783199284173.png",
    videoTitle: "Assets library demo",
    videoDescription: "A video area for explaining how uploaded materials become reusable references across Crelavo projects.",
    videoUrl: "https://cdn.hailuoai.video/moss/prod/2026-07-05-05/video/1783200446193878757-1783200446163.mp4",
    highlights: ["Store images, videos, audio, PDFs and brand files", "Reuse assets across websites, ads, visuals and documents", "Keep brand and product consistency across outputs", "Reduce repetitive uploads for repeat projects"],
    workflow: ["Upload or collect project materials", "Tag them as product, brand, voice, document or video references", "Use the same assets across multiple tools", "Build consistent campaigns from saved materials"],
    bestFor: ["E-commerce brands", "Repeat campaigns", "Brand kits", "Agency workflows"],
    primaryCtaLabel: "Open brand files",
    primaryCtaHref: "/tools/brand-files",
    secondaryCtaLabel: "Open assistant",
    secondaryCtaHref: "/dashboard/assistant-workspace"
  },
  {
    id: "omni-assistant",
    group: "feature",
    title: "Omni Assistant",
    kicker: "One prompt",
    eyebrow: "One request, routed workflow",
    description: "Ask for a website, video, app, avatar, PDF or campaign and Crelavo routes the workflow.",
    longDescription: "Omni Assistant is the central conversation layer for Crelavo. Instead of choosing every tool manually, users describe what they need and Crelavo routes the request into the right production path for video, websites, apps, visuals, documents or campaigns.",
    href: "/showcase/omni-assistant",
    tone: "blue",
    imageUrl: "https://cdn.hailuoai.video/moss/prod/2026-07-05-05/image/1783199309314857013-1783199309311.png",
    videoTitle: "Omni Assistant explainer",
    videoDescription: "A video area for showing how a single user request becomes a structured production plan.",
    videoUrl: "https://cdn.hailuoai.video/moss/prod/2026-07-05-05/video/1783200475974783117-1783200475940.mp4",
    highlights: ["Natural-language production requests", "Routes work into the right tool or production category", "Supports websites, videos, apps, avatars, visuals and documents", "Helps users who do not know where to start"],
    workflow: ["User explains the goal", "Omni identifies the right production type", "Crelavo gathers missing details and assets", "The production flow starts with the right assistant"],
    bestFor: ["New users", "Complex requests", "Cross-format campaigns", "Fast production planning"],
    primaryCtaLabel: "Open Omni Assistant",
    primaryCtaHref: "/dashboard/assistant-workspace",
    secondaryCtaLabel: "Browse tools",
    secondaryCtaHref: "/tools"
  },
  {
    id: "generate-hub",
    group: "feature",
    title: "Generate hub",
    kicker: "Production",
    eyebrow: "Central creation hub",
    description: "Start AI video, talking video, visuals, source packages or brand assets from one place.",
    longDescription: "Generate hub gives users a central starting point for production. From there, they can choose a specific tool or let Crelavo guide them toward the right path for video, visuals, websites, apps, brand files or campaign packages.",
    href: "/showcase/generate-hub",
    tone: "pink",
    imageUrl: "https://cdn.hailuoai.video/moss/prod/2026-07-05-05/image/1783199425743520066-1783199425739.png",
    videoTitle: "Generate hub tour",
    videoDescription: "A video area for walking users through the available production entries and how each one starts.",
    videoUrl: "https://cdn.hailuoai.video/moss/prod/2026-07-05-05/video/1783200506566226583-1783200506537.mp4",
    highlights: ["Central place to start creative work", "Connects tools, categories and assistant workflows", "Reduces confusion between many AI services", "Supports both quick generation and managed production"],
    workflow: ["Choose a production type", "Review the matching workflow", "Provide assets or a short brief", "Launch the request through the right assistant"],
    bestFor: ["First-time users", "Tool discovery", "Quick production starts", "Comparing service categories"],
    primaryCtaLabel: "Browse categories",
    primaryCtaHref: "/categories",
    secondaryCtaLabel: "Open all tools",
    secondaryCtaHref: "/tools"
  },
  {
    id: "live-workspace",
    group: "feature",
    title: "Live workspace",
    kicker: "Tracking",
    eyebrow: "Production tracking",
    description: "Follow provider readiness, output registry, credits and final delivery package status.",
    longDescription: "Live workspace helps users track what is happening after a production request starts. It is designed for ongoing projects where outputs, credits, provider status, revisions and final delivery packages need to stay visible.",
    href: "/showcase/live-workspace",
    tone: "amber",
    imageUrl: "https://cdn.hailuoai.video/moss/prod/2026-07-05-05/image/1783199441797068118-1783199441793.png",
    videoTitle: "Live production tracking preview",
    videoDescription: "A video area for showing project status, output review, delivery packages and revision tracking.",
    highlights: ["Track production progress and output status", "Review credits, provider readiness and final package delivery", "Useful for managed services and multi-step projects", "Keeps production history accessible"],
    workflow: ["Production request starts", "Outputs and status updates appear in the workspace", "User reviews, approves or requests revisions", "Final delivery package is prepared"],
    bestFor: ["Managed production", "Client delivery", "Revision workflows", "Multi-output projects"],
    primaryCtaLabel: "View productions",
    primaryCtaHref: "/dashboard/productions",
    secondaryCtaLabel: "Open assistant",
    secondaryCtaHref: "/dashboard/assistant-workspace"
  }
];

export const categoryShowcaseItems: ShowcaseItem[] = [
  {
    id: "ai-live-sales-agent",
    group: "category",
    title: "AI Live Sales Agent",
    kicker: "Live commerce",
    eyebrow: "Autonomous live-stream brand agents",
    description: "Plan fair-use AI live-stream sales agents that present products, answer chat, push CTAs and support multilingual live commerce.",
    longDescription: "AI Live Sales Agent is a premium live commerce category for brands, Shopify/Amazon/TikTok Shop sellers and creators that want an autonomous avatar host to sell products, answer live chat questions, handle objections and prepare a managed live shopping workflow. The first phase captures product links, avatar persona, voice/language, live FAQ, CTA/discount logic, OBS/provider readiness and compliance notes. Starter, Pro and Agency are service plans with 10/40/120 fair-use live hours, no credit balance and pay-as-you-go provider/API cost analysis for extra usage.",
    href: "/showcase/ai-live-sales-agent",
    tone: "purple",
    imageUrl: "https://cdn.hailuoai.video/moss/prod/2026-07-05-03/image/1783192261949279707-1783192261944.png",
    videoTitle: "AI Live Sales Agent guide",
    videoDescription: "A premium live commerce category for AI avatar hosts, product selling and live chat reply planning.",
    highlights: ["10/40/120 fair-use live hours", "Product-link selling and live chat replies", "Avatar persona, voice and multilingual sales", "$249/$799/$2499 monthly service plans with no included credits"],
    workflow: ["Add product link or product details", "Choose Starter, Pro or Agency live-agent scope", "Define platform, avatar persona, voice, language and live interaction mode", "Review stream setup, FAQ/objection handling, CTA and provider readiness"],
    bestFor: ["TikTok Shop sellers", "Shopify brands", "Amazon sellers", "Influencer agencies"],
    primaryCtaLabel: "Plan live sales agent",
    primaryCtaHref: "/dashboard/assistant-workspace?idea=AI%20live%20sales%20agent%20for%20fair-use%20product%20selling&category=live_sales_agent&mode=media",
    secondaryCtaLabel: "View pricing",
    secondaryCtaHref: "/pricing"
  },
  {
    id: "drone-aerial-video",
    group: "category",
    title: "Drone / Satellite Video",
    kicker: "Aerial style",
    eyebrow: "AI map and drone-style production",
    description: "Create map/location drone-style video requests with route notes, marked satellite areas, voice-over, subtitles and music.",
    longDescription: "Drone / Satellite Video supports map/location flyovers, satellite-view intros, real-estate style aerial direction, travel visuals, city/location promos and drone-style storytelling. Users can provide a location, route/path and marked map or satellite area notes before starting production, then admins can review narration, subtitle, music and provider readiness details.",
    href: "/showcase/drone-aerial-video",
    tone: "cyan",
    imageUrl: "https://cdn.hailuoai.video/moss/prod/2026-07-05-03/image/1783192231039044746-1783192231031.png",
    videoTitle: "Drone-style production preview",
    videoDescription: "A preview area for showing map/location flyover, travel, real estate and aerial-style production concepts.",
    highlights: ["AI map/location drone-style video planning", "Location, route and marked satellite area notes", "Useful for real estate, travel, city and location promos", "Can be combined with voice-over, subtitles and music"],
    workflow: ["User provides location, route, map idea or property/travel brief", "Crelavo records drone location details and marked-area notes", "The request becomes a drone/satellite production package", "Admin/provider workflow prepares preview and delivery"],
    bestFor: ["Real estate promos", "Travel/location videos", "City flyover concepts", "Map-based explainers"],
    primaryCtaLabel: "Plan drone-style video",
    primaryCtaHref: "/dashboard/assistant-workspace?idea=Drone%20style%20aerial%20location%20video&category=drone_video&mode=media",
    secondaryCtaLabel: "View categories",
    secondaryCtaHref: "/categories"
  },
  {
    id: "video-motion",
    group: "category",
    title: "Video & Motion",
    kicker: "17 categories",
    eyebrow: "Video production category",
    description: "AI video, AI live sales agents, drama, short series, drone/satellite, animation, cinematic clips, MV, nature, anime, clipping and video tools.",
    longDescription: "Video & Motion is the category for brands, creators and businesses that need moving content. It covers AI video generation, AI live sales agent planning, drama and short-series workflows, drone/satellite video planning, cinematic clips, animation, music video concepts, product motion, shorts, clipping and social-ready video outputs.",
    href: "/showcase/video-motion",
    tone: "cyan",
    imageUrl: "https://cdn.hailuoai.video/moss/prod/2026-07-05-05/image/1783201093102505723-1783201093100.png",
    videoTitle: "Video & Motion category guide",
    videoDescription: "A video area for explaining which video workflows are available and what users can create.",
    highlights: ["AI video and cinematic clip production", "Animation, MV and social video workflows", "Useful for ads, reels, product explainers and creative campaigns", "Can connect with voice, visuals and brand files"],
    workflow: ["Pick a video goal", "Upload references or describe the idea", "Crelavo routes the request to the right video workflow", "Review outputs and package the final delivery"],
    bestFor: ["Social ads", "Product videos", "Music-video style clips", "Campaign motion assets"],
    primaryCtaLabel: "Start video production",
    primaryCtaHref: "/tools/ai-video-generator",
    secondaryCtaLabel: "View categories",
    secondaryCtaHref: "/categories"
  },
  {
    id: "animation-character-video",
    group: "category",
    title: "Animation & character video",
    kicker: "Characters",
    eyebrow: "Animation production category",
    description: "2D, 3D, anime and cartoon videos using uploaded photos, selected characters or newly created characters.",
    longDescription: "Animation & character video lets users create cartoons, anime-style shorts, character explainers and animated clips from a prompt, uploaded photo/avatar, selected character or newly created character. Voice can come from the user's own recording, a selected AI voice or a newly created AI voice.",
    href: "/showcase/animation-character-video",
    tone: "pink",
    imageUrl: "https://cdn.hailuoai.video/moss/prod/2026-07-05-05/image/1783201093102505723-1783201093100.png",
    videoTitle: "Animation and character video guide",
    videoDescription: "A guide for animation, cartoon and anime-style workflows with photo/avatar input, character choice and voice options.",
    highlights: ["Upload a photo/avatar or choose/create a character", "Use own voice, selected AI voice or new AI voice", "Supports animation, anime, cartoon and character videos", "Can deliver social clips, explainers and short story scenes"],
    workflow: ["Choose animation/anime/cartoon direction", "Upload photo/avatar, choose a character or create a new one", "Select own voice, a ready AI voice or a new voice", "Start production and review final delivery"],
    bestFor: ["Cartoon shorts", "Anime-style scenes", "Character explainers", "Social animation"],
    primaryCtaLabel: "Start animation",
    primaryCtaHref: "/dashboard/assistant-workspace?idea=Animation%20video%20with%20character%20and%20voice%20options&category=animation&mode=media",
    secondaryCtaLabel: "Open categories",
    secondaryCtaHref: "/categories"
  },
  {
    id: "drama-short-series",
    group: "category",
    title: "Drama / Short Series",
    kicker: "Short drama",
    eyebrow: "Drama and viral short-film category",
    description: "One-prompt short drama, mini-series and viral short-film production with characters, dialogue, voice, music and social cuts.",
    longDescription: "Drama / Short Series helps users turn one prompt into a short drama, mini-series episode, viral short film or social-first story video. The workflow can include character roles, episode or scene arc, hook-first opening, dialogue, voice-over, music, subtitles and Reels/TikTok/Shorts delivery notes.",
    href: "/showcase/drama-short-series",
    tone: "pink",
    imageUrl: "https://cdn.hailuoai.video/moss/prod/2026-07-05-05/image/1783201093102505723-1783201093100.png",
    videoTitle: "Drama / Short Series guide",
    videoDescription: "A guide for short drama, mini-series, viral short film and episode-style story workflows.",
    highlights: ["One-prompt drama and short-series setup", "Character roles, dialogue and scene planning", "Voice-over, subtitles and cinematic music options", "Built for TikTok, Reels and YouTube Shorts story delivery"],
    workflow: ["Describe the drama idea or episode premise", "Choose short series, viral short film or episode pack", "Crelavo records characters, dialogue, hook and scene notes", "Review the production request and delivery plan"],
    bestFor: ["Short dramas", "Mini-series concepts", "Viral short films", "Social story videos"],
    primaryCtaLabel: "Create drama video",
    primaryCtaHref: "/dashboard/assistant-workspace?idea=Viral%20short%20drama%20series%20with%20characters%20dialogue%20voice%20and%20music&category=drama&mode=media",
    secondaryCtaLabel: "Open categories",
    secondaryCtaHref: "/categories"
  },
  {
    id: "music-video-self-voice",
    group: "category",
    title: "Music Video / MV",
    kicker: "Music clip",
    eyebrow: "Music and performance video category",
    description: "Music clips, lyric videos and performance visuals with optional uploaded photo/avatar, character and voice choices.",
    longDescription: "Music Video / MV supports lyric videos, visualizers, performance clips and social music cuts. Users can upload their own music or reference, use their own image/voice if they want, or choose/create a character and select/create an AI voice instead.",
    href: "/showcase/music-video-self-voice",
    tone: "purple",
    imageUrl: "https://cdn.hailuoai.video/moss/prod/2026-07-05-05/image/1783199425743520066-1783199425739.png",
    videoTitle: "Music Video / MV guide",
    videoDescription: "A guide for music clips, lyric videos, visualizers and performance-style videos with image and voice options.",
    highlights: ["Use uploaded music or a music reference", "Add own photo/voice or choose/create character and AI voice", "Supports lyric, visualizer, teaser and performance clip styles", "Designed for TikTok, Reels, Shorts and music promo delivery"],
    workflow: ["Upload or describe the song/music direction", "Choose lyric, visualizer, teaser or performance style", "Select photo/avatar, character and voice options", "Package final clip for social delivery"],
    bestFor: ["Music promo", "Lyric videos", "Artist/character clips", "Social MV cuts"],
    primaryCtaLabel: "Create music video",
    primaryCtaHref: "/dashboard/assistant-workspace?idea=Music%20video%20with%20character%20image%20and%20voice%20options&category=music_video&mode=media",
    secondaryCtaLabel: "Open categories",
    secondaryCtaHref: "/categories"
  },
  {
    id: "avatar-cloning",
    group: "category",
    title: "Avatar & Cloning",
    kicker: "4 categories",
    eyebrow: "Avatar production category",
    description: "Talking video, lip-sync, voice clone and visual/style clone production workflows.",
    longDescription: "Avatar & Cloning focuses on human-facing content such as talking videos, lip-sync clips, voice references and reusable visual style. It helps users create presenter-style content, spokesperson clips and consistent identity-driven media.",
    href: "/showcase/avatar-cloning",
    tone: "purple",
    imageUrl: "https://cdn.hailuoai.video/moss/prod/2026-07-05-05/image/1783201113873588204-1783201113869.png",
    videoTitle: "Avatar & Cloning category guide",
    videoDescription: "A video area for showing talking video, lip-sync, voice and visual clone examples.",
    highlights: ["Talking video and lip-sync workflows", "Voice and visual reference support", "Useful for presenter content and explainers", "Can be combined with product or campaign videos"],
    workflow: ["Choose talking video, lip-sync or clone workflow", "Provide script, reference or production goal", "Generate preview content", "Approve and deliver the final clip"],
    bestFor: ["Presenter videos", "Product explainers", "Training content", "Localized spokesperson clips"],
    primaryCtaLabel: "Create talking video",
    primaryCtaHref: "/tools/talking-video",
    secondaryCtaLabel: "Open assistant",
    secondaryCtaHref: "/dashboard/assistant-workspace"
  },
  {
    id: "web-app-software",
    group: "category",
    title: "Web, App & Software",
    kicker: "4 categories",
    eyebrow: "Software production category",
    description: "Websites, SaaS products, mobile apps and admin panel projects with source delivery.",
    longDescription: "Web, App & Software is for users who want more than a design mockup. It covers landing pages, business websites, SaaS applications, mobile app concepts, dashboards and admin systems with production planning and source delivery options.",
    href: "/showcase/web-app-software",
    tone: "green",
    imageUrl: "https://cdn.hailuoai.video/moss/prod/2026-07-05-05/image/1783201130865149241-1783201130862.png",
    videoTitle: "Web, App & Software category guide",
    videoDescription: "A video area for explaining how website and software requests become scoped production projects.",
    highlights: ["Website and landing page builds", "SaaS/app concepts and admin panel workflows", "Source delivery and project packaging", "Useful for businesses launching digital products"],
    workflow: ["Describe the product or business goal", "Crelavo maps pages, features and assets", "Production begins with the right website/app workflow", "Final package is delivered for review or launch"],
    bestFor: ["Startup landing pages", "SaaS MVPs", "Business websites", "Internal dashboards"],
    primaryCtaLabel: "Build website",
    primaryCtaHref: "/tools/website-builder",
    secondaryCtaLabel: "Build SaaS/App",
    secondaryCtaHref: "/tools/saas-app-builder"
  },
  {
    id: "brand-visuals-files",
    group: "category",
    title: "Brand, Visuals & Files",
    kicker: "3 categories",
    eyebrow: "Brand production category",
    description: "Brand kits, visual packs, PDFs, documents, pitch decks and reusable files.",
    longDescription: "Brand, Visuals & Files helps users create reusable brand assets and polished business materials. It supports image packs, visual concepts, brand files, PDFs, pitch decks, documents and campaign-ready creative files.",
    href: "/showcase/brand-visuals-files",
    tone: "pink",
    imageUrl: "https://cdn.hailuoai.video/moss/prod/2026-07-05-05/image/1783201146423541199-1783201146419.png",
    videoTitle: "Brand, Visuals & Files category guide",
    videoDescription: "A video area for showing how visual packs, brand files and documents are created and reused.",
    highlights: ["Brand kits and reusable visual materials", "Image packs, PDFs, decks and documents", "Useful for campaign launches and business communication", "Can feed into website, video and marketing workflows"],
    workflow: ["Define the brand or document need", "Upload logos, product images or references", "Generate visual and file outputs", "Reuse assets in campaigns and production packages"],
    bestFor: ["Brand kits", "Pitch decks", "Visual packs", "Business documents"],
    primaryCtaLabel: "Create visual pack",
    primaryCtaHref: "/tools/image-visual-pack",
    secondaryCtaLabel: "Open brand files",
    secondaryCtaHref: "/tools/brand-files"
  },
  {
    id: "marketing-commerce",
    group: "category",
    title: "Marketing & Commerce",
    kicker: "3 categories",
    eyebrow: "Commerce production category",
    description: "Campaigns, product links, localization, growth workflows and AI agents.",
    longDescription: "Marketing & Commerce is for campaigns that need assets, messaging and conversion-focused outputs. It can turn Shopify, Amazon or Trendyol product links into product videos, ad concepts, visuals, landing pages and campaign delivery packages.",
    href: "/showcase/marketing-commerce",
    tone: "amber",
    imageUrl: "https://cdn.hailuoai.video/moss/prod/2026-07-05-05/image/1783201171597890267-1783201171595.png",
    videoTitle: "Marketing & Commerce category guide",
    videoDescription: "A video area for explaining product-link campaigns, ad assets and growth workflows.",
    highlights: ["Product-link to campaign workflows", "Ad videos, visuals and landing page support", "Useful for e-commerce and creator campaigns", "Can combine AI agents, localization and growth assets"],
    workflow: ["Provide product link or campaign goal", "Crelavo extracts key selling points", "Generate visuals, video, copy or page assets", "Package campaign-ready materials"],
    bestFor: ["E-commerce products", "Shopify campaigns", "Amazon/Trendyol products", "Growth experiments"],
    primaryCtaLabel: "Start campaign",
    primaryCtaHref: "/dashboard/assistant-workspace?category=campaign",
    secondaryCtaLabel: "View categories",
    secondaryCtaHref: "/categories"
  }
];

export const showcaseItems = [...featureShowcaseItems, ...categoryShowcaseItems];

export function getShowcaseItem(id: string) {
  return showcaseItems.find((item) => item.id === id);
}
