create table if not exists production_shot_jobs (
  id bigint generated by default as identity primary key,
  production_id uuid not null references production_requests(id) on delete cascade,
  shot_index integer not null check (shot_index > 0),
  idempotency_key text not null,
  status text not null default 'submitting',
  provider_job_id text,
  job_json jsonb not null default '{}'::jsonb,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  unique (production_id, shot_index),
  unique (idempotency_key)
);

create index if not exists production_shot_jobs_production_idx on production_shot_jobs (production_id, shot_index);

alter table production_shot_jobs enable row level security;
