"use client";
import { useMemo, useState } from "react";
import { CATEGORIES, GROUPS, formatPack, getCategory, matchCategoryFromText, type Category } from "@/lib/crelavo/categoryCatalog";
export type ProductionSelection={categoryId:string;type:string;packId:string;features:string[];extras:Record<string,string>};
type Props={onConfirm:(selection:ProductionSelection)=>void;initialCategoryId?:string};
function urlCategory(){if(typeof window==="undefined")return "";const q=new URLSearchParams(window.location.search);const direct=q.get("category")||"";if(direct)return direct;const type=String(q.get("type")||"").toLowerCase().trim();const map:Record<string,string>={media:"video",video:"video","ai video":"video",drone:"drone_video","live_sales":"live_sales_agent",commerce:"campaign",app:"mobile_app",ecommerce:"website",avatar:"avatar",image:"image",documentary:"documentary",animation:"animation"};return map[type]||"";}
export function AssistantPreProduction({onConfirm,initialCategoryId}:Props){const[categoryId,setCategoryId]=useState(initialCategoryId||urlCategory());const[packId,setPackId]=useState("");const[features,setFeatures]=useState<string[]>([]);const[extras,setExtras]=useState<Record<string,string>>({});const[guess,setGuess]=useState("");const[error,setError]=useState("");const category=useMemo(()=>getCategory(categoryId),[categoryId]);function pick(next:Category){setCategoryId(next.id);setPackId(next.packs.length===1?next.packs[0].id:"");setFeatures([]);setExtras({});setError("");history.replaceState({},"",`?category=${encodeURIComponent(next.id)}&type=${encodeURIComponent(next.type)}`);}function confirm(){if(!category||!packId){setError("Pick a category and package first.");return;}const missing=category.extras.find((field)=>field.required&&!extras[field.id]?.trim());if(missing){setError(`Select ${missing.label.toLowerCase()} first.`);return;}onConfirm({categoryId:category.id,type:category.type,packId,features,extras});}if(!category)return <div className="card" style={{maxWidth:980,margin:"24px auto",padding:24}}><p className="kicker">Assistant pre-production</p><h1>What do you want to produce?</h1><p style={{opacity:0.72}}>No production type is selected yet. Choose one below to continue.</p><p>Choose the category first. The production canvas opens after these choices.</p><div style={{display:"flex",gap:8,margin:"16px 0"}}><input value={guess} onChange={e=>setGuess(e.target.value)} placeholder="Try: outdoor avatar video" style={{flex:1}}/><button className="btn" type="button" onClick={()=>{const found=matchCategoryFromText(guess);if(found)pick(found);else setError("Pick a category below.");}}>Match</button></div>{error?<p className="form-message">{error}</p>:null}{GROUPS.map(group=><section key={group.id} style={{marginTop:20}}><h2>{group.label}</h2><p>{group.blurb}</p><div style={{display:"flex",flexWrap:"wrap",gap:8}}>{CATEGORIES.filter(c=>c.group===group.id).map(c=><button className="btn secondary" type="button" key={c.id} onClick={()=>pick(c)}>{c.label}</button>)}</div></section>)}</div>;
return <div className="card" style={{maxWidth:980,margin:"24px auto",padding:24}}><p className="kicker">Selected production: {category.label}</p><h1>Set options before production</h1><button className="btn secondary" type="button" onClick={()=>setCategoryId("")}>Change category</button><h2>Package</h2><div style={{display:"flex",flexWrap:"wrap",gap:8}}>{category.packs.map(pack=><button className={pack.id===packId?"btn":"btn secondary"} type="button" key={pack.id} onClick={()=>setPackId(pack.id)}>{pack.label} · {formatPack(pack)}</button>)}</div><h2>Features</h2><div style={{display:"flex",flexWrap:"wrap",gap:8}}>{category.features.map(feature=><button className={features.includes(feature.id)?"btn":"btn secondary"} type="button" key={feature.id} onClick={()=>setFeatures(current=>current.includes(feature.id)?current.filter(id=>id!==feature.id):[...current,feature.id])}>{feature.label}</button>)}</div>{category.extras.map(field=><label key={field.id} style={{display:"grid",gap:6,marginTop:14}}>{field.label}{field.required?" *":""}{field.kind==="select"?<select value={extras[field.id]||""} onChange={e=>setExtras(current=>({...current,[field.id]:e.target.value}))}><option value="">Select</option>{field.options?.map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</select>:<input value={extras[field.id]||""} placeholder={field.placeholder} onChange={e=>setExtras(current=>({...current,[field.id]:e.target.value}))}/>}</label>)}{error?<p className="form-message">{error}</p>:null}<button className="btn" type="button" style={{marginTop:20}} onClick={confirm}>Continue to production</button></div>;
}
