"use client";

import { useEffect, useRef, useState } from "react";
import { supabaseBrowser } from "@/lib/supabase";

type JobView = { id:string; category:string; typeName:string; status:string; chargedTotal:number; previewKind:string; previewHtml:string; files:{name:string;mime:string;text:string}[]; liveSalesHref:string|null };
const COPY_PARTS=["Copy / layout"];
const ENGINE_PARTS=["Voice","Environment","Product","Scene","Face","Wardrobe"];
const ACTIVE_PATHS=["/dashboard/create","/dashboard/assistant-workspace"];

function activePath(){return typeof location!=="undefined"&&ACTIVE_PATHS.some(path=>location.pathname.startsWith(path))}
function cyanSelected(el:Element){const m=getComputedStyle(el).backgroundColor.match(/\d+/g);if(!m||m.length<3)return false;const [r,g,b]=m.map(Number);return b>170&&g>110&&r<90}
function readChips(){return Array.from(document.querySelectorAll("button")).filter(b=>cyanSelected(b)&&(b.textContent||"").trim().length<28).map(b=>(b.textContent||"").trim()).filter(Boolean)}
function findComposer(){const nodes=Array.from(document.querySelectorAll("textarea,input"));const ta=nodes.find(el=>/describe what to make/i.test((el as HTMLInputElement).placeholder||"")) as HTMLTextAreaElement|HTMLInputElement|undefined;if(!ta)return null;const form=ta.closest("form");const root=form||ta.parentElement;const buttons=root?Array.from(root.querySelectorAll("button")):[];return{ta,form,send:buttons[buttons.length-1]||null}}
function normalizeCategory(value:string){const v=value.toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"");const aliases:Record<string,string>={ai_video:"video",website_saas:"website",mobile:"mobile_app",admin:"admin_project",talking:"talking_video",cinematic:"cinematic_video",clipping:"video_clipping",tools:"video_tools",ad_score:"ad_score_checker",calendar:"campaign_calendar",agent:"ai_agent",cultural:"cultural_localization",live_sales:"live_sales_agent",voice:"voice_clone",document:"document_pack",anime:"anime_short_film",animal:"animal_video",nature:"nature_video",space:"planet_space_video",drone:"drone_video",stickman:"stickman_animation"};return aliases[v]||v||"video"}
async function authHeaders():Promise<Record<string,string>>{const {data}=await supabaseBrowser().auth.getSession();const token=data.session?.access_token;return token?{authorization:`Bearer ${token}`}:{}}
async function api(body?:Record<string,unknown>){const headers={...(await authHeaders()),...(body?{"content-type":"application/json"}:{})};const res=await fetch("/api/assistant-work",{method:body?"POST":"GET",headers,credentials:"same-origin",body:body?JSON.stringify(body):undefined});const data=await res.json().catch(()=>({ok:false,message:"Production request failed."}));return{res,data}}
function clearComposer(el:HTMLTextAreaElement|HTMLInputElement){const proto=el instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,"value")?.set?.call(el,"");el.dispatchEvent(new Event("input",{bubbles:true}));el.placeholder="What should change?"}

export function AssistantWorkBoot(){
  const [balance,setBalance]=useState<number|null>(null),[quoteCredits,setQuoteCredits]=useState(0),[job,setJob]=useState<JobView|null>(null),[busy,setBusy]=useState(false),[warning,setWarning]=useState(""),[part,setPart]=useState("Scene");
  const jobRef=useRef<JobView|null>(null),partRef=useRef(part),bound=useRef(new WeakSet<EventTarget>());
  useEffect(()=>{jobRef.current=job},[job]); useEffect(()=>{partRef.current=part},[part]);
  useEffect(()=>{
    if(!activePath())return;
    const params=new URLSearchParams(location.search),category=normalizeCategory(params.get("category")||"video"),typeName=params.get("type")||"";
    const refreshQuote=async(mode:"produce"|"revise",message="")=>{const {data}=await api({action:"quote",category,typeName,chips:readChips(),mode,message});if(typeof data.balance==="number")setBalance(data.balance);if(typeof data.credits==="number")setQuoteCredits(data.credits)};
    api().then(({data})=>{if(typeof data.balance==="number")setBalance(data.balance)}).catch(()=>{}); refreshQuote("produce");
    const onSend=async(e:Event)=>{const composer=findComposer();if(!composer)return;const message=(composer.ta.value||"").trim();if(!message)return;e.preventDefault();e.stopPropagation();if("stopImmediatePropagation"in e)e.stopImmediatePropagation();setBusy(true);setWarning("");const current=jobRef.current;const {data}=await api({action:current?"revise":"produce",category,typeName,chips:readChips(),message:current?`${partRef.current}: ${message}`:message,jobId:current?.id});setBusy(false);if(data.code==="sign_in"){location.href="/?auth=login";return}if(!data.ok){setWarning(data.message||"Credits empty. Production stopped.");if(typeof data.balance==="number")setBalance(data.balance);if(data.job)setJob(data.job);return}if(typeof data.balance==="number")setBalance(data.balance);if(data.job)setJob(data.job);if(data.warning)setWarning(data.warning);clearComposer(composer.ta);refreshQuote("revise")};
    const bind=()=>{const c=findComposer();if(!c)return;for(const target of [c.send,c.ta]){if(!target||bound.current.has(target))continue;bound.current.add(target);if(target===c.send)target.addEventListener("click",onSend,true);else target.addEventListener("keydown",(event:Event)=>{const key=event as KeyboardEvent;if(key.key==="Enter"&&!key.shiftKey)onSend(key)},true)}};
    bind();const timer=window.setInterval(bind,500);return()=>window.clearInterval(timer)
  },[]);
  if(typeof window!=="undefined"&&!activePath())return null;
  const download=async()=>{if(!job)return;const {data}=await api({action:"deliver",jobId:job.id,category:job.category});if(!data.ok||!data.zipB64)return;const bin=Uint8Array.from(atob(data.zipB64),(c:string)=>c.charCodeAt(0)),blob=new Blob([bin],{type:"application/zip"}),a=document.createElement("a");const url=URL.createObjectURL(blob);a.href=url;a.download=data.zipName||"crelavo.zip";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);if(data.job)setJob(data.job)};
  return <><style>{`.caw-dock{position:fixed;left:50%;transform:translateX(-50%);bottom:118px;z-index:35;color:#aeb8cc;font:12px Inter,system-ui;background:rgba(7,11,24,.9);border:1px solid #1e293b;border-radius:999px;padding:6px 12px}.caw-stage{position:fixed;top:64px;left:0;right:0;bottom:150px;overflow:auto;background:#070b18;z-index:25;padding:20px 24px 12px}.caw-top{display:flex;gap:12px;align-items:center;justify-content:space-between;margin-bottom:12px;color:#f8fbff;font:14px Inter,system-ui}.caw-btn{background:#0ea5e9;color:#072033;border:0;border-radius:999px;font-weight:700;padding:8px 14px;cursor:pointer}.caw-btn[disabled]{opacity:.45}.caw-ghost{background:transparent;color:#f8fbff;border:1px solid #1e293b;border-radius:999px;padding:8px 14px}.caw-warn{background:#0b1220;border:1px solid #0ea5e9;color:#f8fbff;border-radius:12px;padding:12px 14px;margin-bottom:12px}.caw-warn a{color:#0ea5e9}.caw-parts{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.caw-chip{border:1px solid #1e293b;background:#0b1220;color:#aeb8cc;border-radius:999px;padding:6px 10px;cursor:pointer;font-size:12px}.caw-chip.on{background:#0ea5e9;color:#072033;border-color:#0ea5e9}.caw-frame{width:100%;min-height:52vh;border:1px solid #1e293b;border-radius:16px;background:#0b1220}`}</style><div className="caw-dock">{busy?"Producing…":`Uses ${quoteCredits} credits`}{balance!=null?` · Balance ${balance.toLocaleString("en-US")}`:""}</div>{job?<div className="caw-stage"><div className="caw-top"><div>{job.typeName||job.category} · {job.status==="halted_empty"?"Stopped":"Live preview"}</div><div>{job.liveSalesHref?<a className="caw-ghost" href={job.liveSalesHref}>Open Live Sales</a>:<button className="caw-btn" onClick={download} disabled={busy}>Download files</button>}</div></div>{warning?<div className="caw-warn">{warning} <a href="/dashboard/credits">Add credits</a></div>:null}<div className="caw-parts">{COPY_PARTS.concat(ENGINE_PARTS).map(p=><button key={p} className={part===p?"caw-chip on":"caw-chip"} onClick={()=>setPart(p)} type="button">{p}{COPY_PARTS.includes(p)?" · free":""}</button>)}</div><iframe className="caw-frame" sandbox="allow-popups allow-top-navigation-by-user-activation" title="Live preview" srcDoc={job.previewHtml}/></div>:warning?<div className="caw-stage"><div className="caw-warn">{warning} <a href="/dashboard/credits">Add credits</a></div></div>:null}</>
}