"use client";

import { useEffect } from "react";
import { supabaseBrowser } from "@/lib/supabase";

const API="/api/assistant-work",THREAD="crelavo-aw-thread",STORE="crelavo-aw-last-v2";
let busy=false,jobId="",lastHtml="",lastBrief="";
type Data={ok?:boolean;code?:string;message?:string;charged?:number;balance?:number;available?:number;zipB64?:string;zipBase64?:string;zipName?:string;job?:{id?:string;previewHtml?:string;files?:Array<{name:string;mime?:string;text?:string;content?:string}>};previewHtml?:string;files?:Array<{name:string;mime?:string;text?:string;content?:string}>};
function meta(){const q=new URLSearchParams(location.search);return{type:q.get("type")||"Website",category:q.get("category")||"website"}}
function field(){const nodes=Array.from(document.querySelectorAll<HTMLElement>('textarea,input[type="text"],input:not([type]),[contenteditable="true"]'));return nodes.find(n=>{const s=((n.getAttribute("placeholder")||"")+" "+(n.getAttribute("aria-label")||"")).toLowerCase();return s.includes("describe what to make")||s.includes("what should we make")||s.includes("message")})||nodes.filter(n=>{const r=n.getBoundingClientRect();return r.width>80&&r.height>20&&r.bottom>0&&r.top<innerHeight}).at(-1)||null}
function read(){const e=field();if(!e)return"";return e instanceof HTMLTextAreaElement||e instanceof HTMLInputElement?e.value.trim():(e.innerText||e.textContent||"").trim()}
function clear(){const e=field();if(!e)return;if(e instanceof HTMLTextAreaElement||e instanceof HTMLInputElement){const p=e instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(p,"value")?.set?.call(e,"");e.dispatchEvent(new Event("input",{bubbles:true}));e.dispatchEvent(new Event("change",{bubbles:true}))}else{e.textContent="";e.dispatchEvent(new Event("input",{bubbles:true}))}}
function skip(target:EventTarget|null){if(!(target instanceof Element))return false;const n=target.closest("a,button,[role='button'],svg")||target,s=`${n.getAttribute("aria-label")||""} ${n.getAttribute("title")||""} ${n.textContent||""} ${n.getAttribute("href")||""}`.toLowerCase(),raw=(n.textContent||"").trim();return !!n.closest(`#${THREAD}`)||(/\blive\b/.test(s)&&!/deliver|preview|files/.test(s))||/\$9\.99|\bpro\b\s*\$|\/pricing|view plans|coffee landing|studio site|does not start production|attach|upload/.test(s)||raw==="+"||raw==="Outputs"}
function sendClick(target:EventTarget|null){if(!(target instanceof Element)||skip(target))return false;const btn=target.closest("button,[role='button']"),c=field();if(!btn||!c)return false;const label=`${btn.getAttribute("aria-label")||""} ${btn.getAttribute("title")||""} ${btn.textContent||""}`.toLowerCase();if(/send|arrow.?up|↑|⬆/.test(label))return true;const a=btn.getBoundingClientRect(),b=c.getBoundingClientRect();return Math.abs(a.top+a.height/2-(b.top+b.height/2))<36&&a.left>=b.right-12&&a.width<=64&&a.height<=64}
function ensure(){let t=document.getElementById(THREAD) as HTMLElement|null;if(t)return t;t=document.createElement("div");t.id=THREAD;Object.assign(t.style,{position:"fixed",top:"108px",left:"16px",right:"16px",bottom:"156px",zIndex:"2147483000",background:"rgb(7,11,24)",overflow:"auto",color:"#e8eefc",border:"1px solid rgba(34,211,238,.45)",borderRadius:"16px",boxShadow:"0 24px 80px rgba(0,0,0,.55)",padding:"16px 20px",fontFamily:"ui-sans-serif,system-ui",display:"flex",flexDirection:"column",gap:"12px"});document.body.appendChild(t);return t}
function bubble(side:"user"|"assistant",text:string){const e=document.createElement("div");e.dataset.awBubble=side;Object.assign(e.style,{alignSelf:side==="user"?"flex-end":"stretch",maxWidth:side==="user"?"72%":"100%",background:side==="user"?"rgba(34,211,238,.14)":"rgba(255,255,255,.04)",border:"1px solid rgba(255,255,255,.08)",borderRadius:"16px",padding:"12px 14px",whiteSpace:"pre-wrap",lineHeight:"1.45"});e.textContent=text;ensure().appendChild(e);ensure().scrollTop=ensure().scrollHeight;return e}
function htmlOf(d:Data){if(d.previewHtml)return d.previewHtml;if(d.job?.previewHtml)return d.job.previewHtml;for(const f of d.files||d.job?.files||[]){const x=f.content||f.text;if(x&&(/html/i.test(f.name)||f.mime?.includes("html")))return x}return""}
function button(label:string,fn:()=>void){const b=document.createElement("button");b.type="button";b.textContent=label;Object.assign(b.style,{background:"transparent",color:"#67e8f9",border:"1px solid rgba(103,232,249,.35)",borderRadius:"999px",padding:"6px 10px",cursor:"pointer"});b.onclick=e=>{e.preventDefault();e.stopPropagation();fn()};return b}
function actions(parent:HTMLElement){const row=document.createElement("div");Object.assign(row.style,{display:"flex",gap:"8px",flexWrap:"wrap",marginTop:"12px"});for(const p of ["copy","layout","color"])row.appendChild(button(`${p[0].toUpperCase()+p.slice(1)} · Free`,()=>void run("revise",p)));row.appendChild(button("Download files",()=>void run("deliver")));parent.appendChild(row)}
function render(target:HTMLElement,http:number,d:Data){target.replaceChildren();const h=htmlOf(d);if(h){lastHtml=h;target.append(d.message||"Preview ready.");const f=document.createElement("iframe");f.setAttribute("sandbox","");f.srcdoc=h;Object.assign(f.style,{display:"block",width:"100%",height:"420px",marginTop:"10px",border:"1px solid rgba(255,255,255,.12)",borderRadius:"12px",background:"#fff"});target.appendChild(f)}else target.append(d.message||d.code||JSON.stringify(d)||"No preview returned.");const m=document.createElement("div");m.style.cssText="margin-top:8px;opacity:.7;font-size:12px";m.textContent=`http ${http}${d.code?` · ${d.code}`:""}${d.charged!=null?` · charged ${d.charged}`:""}${(d.available??d.balance)!=null?` · available ${d.available??d.balance}`:""}`;target.appendChild(m);actions(target);try{sessionStorage.setItem(STORE,JSON.stringify({brief:lastBrief,http,data:d,jobId,html:lastHtml}))}catch{}}
async function post(body:Record<string,unknown>){const {data:s}=await supabaseBrowser().auth.getSession();const headers:Record<string,string>={"content-type":"application/json",accept:"application/json"};if(s.session?.access_token)headers.authorization=`Bearer ${s.session.access_token}`;const r=await fetch(API,{method:"POST",credentials:"include",headers,body:JSON.stringify(body)}),raw=await r.text();let d:Data;try{d=raw?JSON.parse(raw):{}}catch{d={ok:false,code:"parse",message:raw||"Invalid JSON"}}return{r,d}}
async function run(action:"produce"|"revise"|"deliver",part?:string,brief=lastBrief){if(busy||action==="produce"&&!brief)return;busy=true;const a=bubble("assistant",action==="produce"?"Starting production…":action==="revise"?"Updating…":"Preparing files…");try{const q=meta(),body:Record<string,unknown>={action,type:q.type,typeName:q.type,category:q.category,jobId,workId:jobId};if(brief){body.brief=brief;body.message=part?`${part}: ${brief}`:brief}if(part)body.part=part;const {r,d}=await post(body);if(d.job?.id)jobId=d.job.id;if(action==="deliver"&&(d.zipB64||d.zipBase64)){const bin=atob(d.zipB64||d.zipBase64||""),bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);const x=document.createElement("a");x.href=URL.createObjectURL(new Blob([bytes]));x.download=d.zipName||"crelavo.zip";x.click()}render(a,r.status,d)}catch(e){a.textContent=e instanceof Error?e.message:"Network error"}finally{busy=false}}
function start(){const brief=read();if(!brief||busy)return;lastBrief=brief;const u=bubble("user",brief);requestAnimationFrame(()=>{if(document.body.contains(u))clear()});void run("produce",undefined,brief)}
function restore(){try{const s=JSON.parse(sessionStorage.getItem(STORE)||"null") as {brief?:string;http?:number;data?:Data;jobId?:string;html?:string}|null;if(!s?.data)return;lastBrief=s.brief||"";jobId=s.jobId||s.data.job?.id||"";lastHtml=s.html||htmlOf(s.data);if(lastBrief)bubble("user",lastBrief);render(bubble("assistant","Restoring…"),s.http||200,s.data)}catch{}}

export default function AssistantWorkBoot(){useEffect(()=>{restore();const key=(e:KeyboardEvent)=>{if(e.key!=="Enter"||e.shiftKey||e.repeat||e.isComposing||skip(e.target))return;const c=field();if(!c||e.target!==c&&!(e.target instanceof Node&&c.contains(e.target))||!read())return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();start()};const click=(e:MouseEvent)=>{if(skip(e.target)||!sendClick(e.target)||!read())return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();start()};const submit=(e:Event)=>{if(skip(e.target)||!read())return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();start()};window.addEventListener("keydown",key,true);window.addEventListener("click",click,true);window.addEventListener("submit",submit,true);return()=>{window.removeEventListener("keydown",key,true);window.removeEventListener("click",click,true);window.removeEventListener("submit",submit,true)}},[]);return <div aria-hidden style={{position:"absolute",width:1,height:1,overflow:"hidden",clip:"rect(0 0 0 0)"}}>Sign in to start production. Copy · Free Layout · Free Color · Free Download files</div>}
