import { readFileSync } from "node:fs";
import { join } from "node:path";

const guardedFiles = [
  "src/components/AdminProductionsTable.tsx",
  "src/app/admin/packages/page.tsx",
  "src/components/AdsRoasPanel.tsx",
  "src/components/ProductionRequestForm.tsx",
  "src/components/ProviderReadinessCard.tsx",
  "src/components/AdminUsersManager.tsx",
  "src/app/admin/payments/page.tsx",
  "src/components/UserInfoPill.tsx",
  "src/app/admin/connections/page.tsx",
  "src/app/admin/users/page.tsx",
  "src/lib/credit-resolution.ts",
  "src/app/api/productions/revision/route.ts",
  "src/components/LoginForm.tsx",
  "src/components/RegisterForm.tsx",
  "src/lib/admin.ts",
  "src/app/admin/page.tsx",
  "src/components/ForgotPasswordForm.tsx",
  "src/components/ResetPasswordForm.tsx",
  "src/app/admin/bulk/page.tsx",
  "src/components/AdminCategoryManager.tsx",
  "src/components/AdminProductionTypePage.tsx"
];

const forbiddenVisibleTerms = [
  "Bekliyor",
  "Otomasyon kuyruğunda",
  "Otomasyon çalışıyor",
  "Hazır",
  "Başarısız",
  "İptal",
  "Müdahale gerekiyor",
  "Teslim edildi",
  "Kuyrukta",
  "Çalışıyor",
  "Otomatik üretim akışı",
  "Aktif provider job",
  "Genel otomasyon",
  "Modül detayı yok",
  "Mağaza seçilmemiş",
  "E-ticaret hedefi yok",
  "Paket düzenleme",
  "Kredi satın alma paketleri",
  "Üretim paketleri",
  "Düzenle",
  "Hesap Bağlama",
  "Sosyal reklam",
  "Günlük bütçe",
  "Performans uyarıları",
  "Yeni hook videosu üret",
  "Hazır üretimleri aç",
  "Eksik",
  "Provider durumu",
  "Gerçek üretim bağlantıları",
  "Kontrol ediliyor",
  "Onaylı ses",
  "Tekrar kontrol et",
  "Düşük maliyetli",
  "Üye ara",
  "Üye listesi",
  "Ad Soyad",
  "E-posta Onayı",
  "Kayıt Tarihi",
  "Son Giriş",
  "Para Karşılığı",
  "Seçilen kullanıcı",
  "Kullanıcı ID",
  "Toplam kredi",
  "Rezerve kredi",
  "Kullanılabilir",
  "Hukuki Sözleşme",
  "Kredi miktarı",
  "İşlem notu",
  "Kredi yükle",
  "Kredi çıkar",
  "Otomatik ödeme",
  "Ödeme sonrası",
  "Demo Kullanıcı",
  "Üye girişi",
  "Kayıt ol",
  "Çıkış yap",
  "Bağlı Hesaplar",
  "Sosyal hesap",
  "Mağaza",
  "Admin rolü",
  "Sosyal reklam ve yayın",
  "E-ticaret mağazaları",
  "Reklam / sosyal",
  "Üyeler",
  "Üye arama",
  "Rezerve kredi admin",
  "maliyetli revizyon",
  "Başlangıç",
  "Tüm Talepler",
  "Metinden Kampanyaya",
  "Global Lokalizasyon",
  "Web Sitesi",
  "Uygulama",
  "Görsel / Medya",
  "Doküman / Dosya",
  "Toplu Üretim",
  "Kredi İşlemleri",
  "Paketler",
  "Kategori Kartları",
  "Reklam Alanları",
  "Görünüm / Tema",
  "Kod Yedekleme",
  "Kontrol merkezi",
  "Site yönetimi",
  "Admin modülü",
  "Modülü aç",
  "Giriş yapılıyor",
  "Google ile devam",
  "E-posta",
  "Şifre",
  "Şifremi unuttum",
  "Kayıt oluşturuluyor",
  "Şifre yenileme",
  "Gönderiliyor",
  "Yeni şifre",
  "Güncelleniyor",
  "Toplu Üretim",
  "validasyon",
  "Risk kontrolü",
  "Kartı düzenle",
  "Aktif kategori kartı",
  "Kart başlığı",
  "Başlangıç kredisi",
  "Değişiklikleri uygula",
  "Yeni kategori",
  "Kontrol listesi",
  "Bu sayfada",
  "Otomasyon sinyali",
  "İlgili otomasyon",
  "sıra dışı",
  "production taleplerine"
];

for (const file of guardedFiles) {
  const content = readFileSync(join(process.cwd(), file), "utf8");
  for (const term of forbiddenVisibleTerms) {
    if (content.includes(term)) {
      throw new Error(`${file} contains non-English visible UI term: ${term}`);
    }
  }
}

console.log("english-ui-guard-smoke ok");
