import { readFileSync } from "node:fs";
import { join } from "node:path";

const example = readFileSync(join(process.cwd(), ".env.example"), "utf8");
const requiredKeys = [
  "NEXT_PUBLIC_APP_URL",
  "ADMIN_EMAIL",
  "PAYMENT_NOTIFICATION_EMAIL",
  "NEXT_PUBLIC_SUPABASE_URL",
  "NEXT_PUBLIC_SUPABASE_ANON_KEY",
  "SUPABASE_SERVICE_ROLE_KEY",
  "STRIPE_SECRET_KEY",
  "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY",
  "STRIPE_WEBHOOK_SECRET",
  "CREDIT_VALUE_USD",
  "TARGET_COST_RATIO",
  "OPENAI_API_KEY",
  "OPENAI_ASSISTANT_MODEL",
  "OPENAI_IMAGE_MODEL",
  "OPENAI_AD_MODEL",
  "ELEVENLABS_API_KEY",
  "ELEVENLABS_VOICE_ID",
  "ELEVENLABS_SOCIAL_VOICE_ID",
  "ELEVENLABS_MALE_VOICE_ID",
  "ELEVENLABS_MODEL_ID",
  "SHOTSTACK_API_KEY",
  "SHOTSTACK_API_URL",
  "VIDEO_PROVIDER",
  "GENERATION_PROVIDER",
  "REPLICATE_API_TOKEN",
  "REPLICATE_MODEL",
  "REPLICATE_VIDEO_VERSION",
  "VIDEO_PROVIDER_ACTIVE_JOB_LIMIT",
  "FAL_KEY",
  "FAL_API_KEY",
  "FAL_VIDEO_MODEL",
  "RUNWAY_API_KEY",
  "RUNWAY_API_VERSION",
  "KLING_API_KEY",
  "KLING_API_URL",
  "KLING_STATUS_API_URL",
  "SUPABASE_PROVIDER_ASSETS_BUCKET",
  "RESEND_API_KEY",
  "SUPPORT_EMAIL",
  "SUPPORT_FROM_EMAIL",
  "R2_ACCOUNT_ID",
  "R2_ACCESS_KEY_ID",
  "R2_SECRET_ACCESS_KEY",
  "R2_BUCKET_NAME",
  "R2_PUBLIC_URL",
  "INNGEST_EVENT_KEY",
  "INNGEST_SIGNING_KEY",
  "META_APP_ID",
  "META_APP_SECRET",
  "META_SYSTEM_ACCESS_TOKEN",
  "META_AD_ACCOUNT_ID",
  "TIKTOK_CLIENT_KEY",
  "TIKTOK_CLIENT_SECRET",
  "TIKTOK_ACCESS_TOKEN",
  "TIKTOK_ADVERTISER_ID",
  "HEYGEN_API_KEY",
  "HEYGEN_VIDEO_TRANSLATE_URL",
  "BULK_GENERATION_CONCURRENCY"
];

const missing = requiredKeys.filter((key) => !new RegExp(`^${key}=`, "m").test(example));
if (missing.length > 0) {
  throw new Error(`.env.example missing keys: ${missing.join(", ")}`);
}

console.log("env-example-smoke ok");
