import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { compactMiniMaxPrompt, MINIMAX_SAFE_PROMPT_CHARS, miniMaxProductionSettings, miniMaxSegmentDurations } from "../src/lib/providers/minimax-production-settings.ts";

const selected = { aspectRatio: "9:16", quality: "1080p", providerPrompt: "User's exact production prompt" };
const fiveSeconds = miniMaxProductionSettings({ selected: { aspectRatio: "9:16", quality: "normal" }, durationSeconds: "5 sec" });
assert.equal(fiveSeconds.duration, 5);
assert.equal(fiveSeconds.ratio, "9:16");
assert.equal(fiveSeconds.resolution, "768P");
const eightSeconds = miniMaxProductionSettings({ selected, durationSeconds: "8 sec" });
assert.equal(eightSeconds.model, "MiniMax-H3");
assert.equal(eightSeconds.duration, 8);
assert.equal(eightSeconds.ratio, "9:16");
assert.equal(eightSeconds.resolution, "2K");
assert.equal(eightSeconds.providerPrompt, selected.providerPrompt);

const fifteenSeconds = miniMaxProductionSettings({ selected: { aspect_ratio: "9:16", quality: "ordinary", provider_prompt: "15-second brief" }, durationSeconds: 15 });
assert.equal(fifteenSeconds.duration, 15);
assert.equal(fifteenSeconds.ratio, "9:16");
assert.equal(fifteenSeconds.resolution, "768P");
assert.equal(fifteenSeconds.providerPrompt, "15-second brief");

const testMode = miniMaxProductionSettings({ selected: { quality: "ordinary", aspectRatio: "9:16" }, durationSeconds: 15, testMode: true, prompt: "Test prompt" });
assert.equal(testMode.duration, 5);
assert.equal(testMode.ratio, "9:16");
assert.equal(testMode.resolution, "768P");
assert.equal(testMode.providerPrompt, "Test prompt");
const longPrompt = `CORE SCENE: ${"important scene detail. ".repeat(500)} FINAL SEGMENT BEAT: continue the action without repeating the previous segment.`;
const compactedPrompt = compactMiniMaxPrompt(longPrompt);
assert.ok(compactedPrompt.length <= MINIMAX_SAFE_PROMPT_CHARS, "MiniMax prompt must stay below the safe provider budget");
assert.match(compactedPrompt, /CORE SCENE/);
assert.match(compactedPrompt, /FINAL SEGMENT BEAT/);
assert.match(compactedPrompt, /compacted/);
assert.equal(miniMaxProductionSettings({ prompt: longPrompt }).providerPrompt.length <= MINIMAX_SAFE_PROMPT_CHARS, true);
assert.deepEqual(miniMaxSegmentDurations(5), [5]);
assert.deepEqual(miniMaxSegmentDurations(10), [10]);
assert.deepEqual(miniMaxSegmentDurations(15), [15]);
assert.deepEqual(miniMaxSegmentDurations(30), [15, 15]);
assert.deepEqual(miniMaxSegmentDurations(45), [15, 15, 15]);
assert.deepEqual(miniMaxSegmentDurations(60), [15, 15, 15, 15]);
assert.deepEqual(miniMaxSegmentDurations(35), [35]);

const startSource = readFileSync(new URL("../src/app/api/automation/start/route.ts", import.meta.url), "utf8");
const visualsSource = readFileSync(new URL("../src/lib/providers/visuals.ts", import.meta.url), "utf8");
assert.match(startSource, /providerTaskId: visualJob\?\.task_id/);
assert.match(startSource, /task_id: visualJob\?\.task_id/);
assert.match(startSource, /const providerTaskId = "task_id" in providerJob/);
assert.match(visualsSource, /content: \[\{ type: "text", text: settings\.providerPrompt \}\]/);
const workAssistantSource = readFileSync(new URL("../src/components/WorkAssistant.tsx", import.meta.url), "utf8");
assert.match(workAssistantSource, /selectedOptionFlagsForPayload/);
assert.match(workAssistantSource, /output_duration_seconds: outputDurationSeconds/);
assert.match(workAssistantSource, /Voice-over: enabled/);
assert.match(workAssistantSource, /Music: disabled/);
console.log("MiniMax production settings smoke passed");
