import { NextRequest, NextResponse } from "next/server";
export const dynamic = "force-dynamic";export const runtime = "nodejs";
type SlimProduction = {  status: string | null;  url: string;  title: string | null;  spent: boolean;  service: boolean;  taskId: string | null;  provider: string | null;  fallback: boolean;};
function json(data: unknown, status = 200) {  return NextResponse.json(data, { status });}
function str(v: unknown, max = 500) {  if (typeof v !== "string") return "";  return v.slice(0, max);}
function slimProduction(p: unknown): SlimProduction | null {  if (!p || typeof p !== "object") return null;  const o = p as Record<string, unknown>;  const url = str(o.url, 2000);  return {    status: str(o.status, 80) || null,    url,    title: str(o.title, 200) || null,    spent: o.spent === true,    service: o.service === true,    taskId: str(o.taskId ?? o.task_id, 120) || null,    provider: str(o.provider, 80) || null,    fallback: o.fallback === true,  };}
function bearerOf(req: NextRequest) {  const h = req.headers.get("authorization") || req.headers.get("Authorization") || "";  return h.startsWith("Bearer ") ? h.slice(7).trim() : "";}
async function readBody(req: NextRequest) {  try {    const raw = await req.json();    return raw && typeof raw === "object" ? (raw as Record<string, unknown>) : {};  } catch {    return {};  }}
async function recordEvent(row: Record<string, unknown>) {  const url =    process.env.NEXT_PUBLIC_SUPABASE_URL ||    process.env.SUPABASE_URL ||    "";  const key =    process.env.SUPABASE_SERVICE_ROLE_KEY ||    process.env.SUPABASE_SERVICE_KEY ||    "";  if (!url || !key) return { recorded: false, reason: "no_db" as const };
  const tables = [    "production_complete_events",    "assistant_production_events",    "production_events",  ];  const headers = {    apikey: key,    Authorization: "Bearer " + key,    "Content-Type": "application/json",    Prefer: "resolution=merge-duplicates,return=minimal",  };
  for (const table of tables) {    try {      const res = await fetch(url.replace(/\/$/, "") + "/rest/v1/" + table, {        method: "POST",        headers,        body: JSON.stringify(row),      });      if (res.ok || res.status === 201 || res.status === 409) {        return { recorded: true, table };      }    } catch {      /* try next table */    }  }  return { recorded: false, reason: "no_table" as const };}
export async function GET() {  return json({    ok: true,    endpoint: "production-complete",    note: "POST {session, type, production, user_id}. Credits are not deducted. MiniMax and HeyGen are not called.",  });}
export async function POST(req: NextRequest) {  const body = await readBody(req);  const session = str(body.session ?? body.session_id, 160);  const type = str(body.type, 80);  const userId = str(body.user_id ?? body.userId, 120);  const production = slimProduction(body.production);  const token = bearerOf(req);
  const row = {    session_id: session || null,    user_id: userId || null,    type: type || null,    status: production?.status || "ready",    preview_url: production?.url || null,    title: production?.title || null,    spent: production?.spent ?? false,    service: production?.service ?? false,    task_id: production?.taskId || null,    provider: production?.provider || null,    fallback: production?.fallback ?? false,    has_auth: !!token,    created_at: new Date().toISOString(),  };
  // Persistence is best-effort. Missing tables must not 500 the assistant.
  let recorded = false;  let persist: { recorded: boolean; table?: string; reason?: string } = {    recorded: false,    reason: "skipped",  };  if (session || userId) {    persist = await recordEvent(row);    recorded = persist.recorded === true;  }
  return json({    ok: true,    recorded,    session: session || null,    type: type || null,    persist,  });}
